### DISCUSSION TITLE
Ingress is changing POST request to GET requests

### DISCUSSION THREAD

**Discussion by nicoADSP** [Azure/application-gateway-kubernetes-ingress#1639] [Q&A]
Hi everyone,

Below is my Ingress K8 resouce:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app-testing
  annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/issuer: letsencrypt
spec:
  tls:
  - hosts:
    - xxxx.yyy.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: xxxx.yyy.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: service-a
            port:
              number: 80
      - path: /orchestrator
        pathType: Exact
        backend:
          service:
            name: service-b
            port:
              number: 80
```

When I call `xxxx.yyy.cloudapp.azure.com/orchestrator` from a script doing a POST request, they automatically get changed to be a GET request. Below is a log from the API demonstrating the issue:

```
INFO:     10.200.4.6:33768 - "GET /orchestrator HTTP/1.1 405 Not Allowed "
```

The /orchestrator is a POST endpoint. How can I ensure that the request keeps its original Request Method?

Thank you for your help!

Nicholas
