### DISCUSSION TITLE
Multiple names one listener

### DISCUSSION THREAD

**Discussion by plalnol** [Azure/application-gateway-kubernetes-ingress#1643] [General]
I can add many names to one listener both in the portal and through az - I can't do this through ingress.yaml
Currently we have : 
```
spec: 
  tls:     
    - hosts:  
        - firstname.server.com
        - secondname.server.com
      secretName: tls-secret-test
  rules:                             
    - host: firstname.server.com
      http:                 
        paths:
       ...
    - host: secondname.server.com
      http:                 
        paths:
```
Expected:
```
spec: 
 tls:     
    - hosts:  
        - firstname.server.com
        - secondname.server.com
      secretName: tls-secret-test
  rules:                             
    - hosts:
        -  firstname.server.com
        -  secondname.server.com
      http:                 
        paths:
```               

Multiple listeners means multiple rules - its easy if You have 2-3 listeners/rules, its mess when You have over a dozen.
