### ISSUE TITLE
sss-redirect with wildcard certificate fails

### ISSUE THREAD

**Issue by thisispaulsmith** [Azure/application-gateway-kubernetes-ingress#1001]
Using ssl-redirect with a wildcard certificate doesn't appear to be possible.

Example ingress:

```
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: app
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
  spec:
    tls:
      - hosts:
        - '*.domainname.com'
      - secretName: testing-secret
    rules:
    - host: '*.domainname.com'
      http:
        paths:
        - path: /
          backend:
            serviceName: app
            servicePort: 80
```

Results in the error: 

```
E0916 07:57:55.819920       1 controller.go:141] network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRedirectConfigurationTargetListenerWildcardHostNameError" Message="TargetListener fl-0305bf5c21665f3e048e3a27a4ef07bd cannot be associated with RedirectConfiguration /subscriptions/xx/resourceGroupsxx/providers/Microsoft.Network/applicationGateways/xx/sslr-fl-0305bf5c21665f3e048e3a27a4ef07bd since it uses wildcard hostname" Details=[]
```

Should this possible with current versions?

I notice that Listeners have no hostname/hostnames configured even when a host is defined in the ingress. Is this as expected?
