### ISSUE TITLE
Allow custom annotations on the AGIC pod from Helm values

### ISSUE THREAD

**Issue by mrbennett** [Azure/application-gateway-kubernetes-ingress#1021]
**Is your feature request related to a problem? Please describe.**
Many services e.g. datadog use custom annotations on pods to provide extra functionality.  At the moment it is not possible to add our own annotations to the AGIC pod using the helm chart.

**Describe the solution you'd like**
A value in the helm chart that can be used to specify extra annotations on the AGIC pod e.g.

```yaml
appgw:
  ...
  annotations:
    example.io/myAnnotation: annotation
```

_I have already made a change for this just adding this so I can link it in the PR_
