### ISSUE TITLE
Can not run pods with Multiple namespaces having same paths & different hosts 

### ISSUE THREAD

**Issue by prateekchawla** [Azure/application-gateway-kubernetes-ingress#1109]
**Describe the bug**
Can not run pods with Multiple namespaces having same paths & different hosts. 
We are using a single gateway to route traffic to different environments t1 & t2 (namely namespaces). Pods/Services/Ingress/Configmaps deployed in respective namespaces. 
Having 2 different listeners in gateway with different hosts (aks-agw-t2.dev-xyz.com & aks-agw-t1.dev-xyz.com) & its associated rules. 
Issue 1- With deployment, the listeners & rules gets deleted in the app gateway
Issue 2 - backend pools are not being created for all namespaces(that's probably because path is same)
Issue 3 - Gateway is not serving the services. 

**To Reproduce**
Ingress backend defined below
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress-ms-everquotebid
  namespace: t1
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: aks-agw-t1.dev-xyz.com
  - http:
      paths:
      - path:  /ms-everquotebid/*
        backend:
          serviceName: ms-everquotebid-service
          servicePort: 8080

```
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress-ms-everquotebid
  namespace: t2
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: aks-agw-t2.dev-xyz.com
  - http:
      paths:
      - path:  /ms-everquotebid/*
        backend:
          serviceName: ms-everquotebid-service
          servicePort: 8080

```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
Name:         ingress-azure-5d4968dbdf-t4wdl
Namespace:    default
Priority:     0
Node:         aks-agentpool-30824605-0/10.0.0.66
Start Time:   Thu, 14 Jan 2021 11:44:32 +0000
Labels:       aadpodidbinding=ingress-azure
              app=ingress-azure
              pod-template-hash=5d4968dbdf
              release=ingress-azure
Annotations:  checksum/config: 88e857155d556e851c8e8929b8264ca7d25a79d26cc9e33c38a2d02349bd80bd
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.0.0.86
IPs:
  IP:           10.0.0.86
Controlled By:  ReplicaSet/ingress-azure-5d4968dbdf
Containers:
  ingress-azure:
    Container ID:   docker://94db2128d7db4a79b02e66b12258786841a0a5b1ca5d8b73f891583f4c96bc50
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.1
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:cf1df9645ded72127967c99bbf88b758b5b19b698ba18a9ed74c3a7ebf016ef1
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 14 Jan 2021 11:44:44 +0000
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-5d4968dbdf-t4wdl (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-bqzz8 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-token-bqzz8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-bqzz8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                     Age                   From                       Message
  ----     ------                     ----                  ----                       -------
  Warning  FailedApplyingAppGwConfig  87s (x13 over 5h27m)  azure/application-gateway  network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPathsWithinUrlPathMapMustBeUnique" Message="Paths specified in a UrlPathMap must be unique. Path /ms-everquotebid/* is already specified in another PathRule in UrlPathMap /subscriptions/bf287ccd-441f-4ca4-b3f4-45263e5be385/resourceGroups/aks-rtb-dev/providers/Microsoft.Network/applicationGateways/applicationgateway20bd/urlPathMaps/url-e1903c8aa3446b7b3207aec6d6ecba8a." Details=[]
* Output of `kubectl logs <ingress controller>. 
I0114 18:25:55.757161       1 mutate_app_gateway.go:164] cache: Config has NOT changed! No need to connect to ARM.
I0114 18:25:55.757183       1 controller.go:151] Completed last event loop run in: 186.282686ms
I0114 18:25:56.833831       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0114 18:26:27.572488       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0114 18:26:27.572513       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0114 18:26:27.573412       1 mutate_app_gateway.go:204] END AppGateway deployment
I0114 18:26:27.573429       1 controller.go:151] Completed last event loop run in: 30.816120196s
I0114 18:26:28.681447       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0114 18:26:28.961622       1 mutate_app_gateway.go:183] END AppGateway deployment
E0114 18:26:28.961806       1 controller.go:141] network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPathsWithinUrlPathMapMustBeUnique" Message="Paths specified in a UrlPathMap must be unique. Path /ms-everquotebid/* is already specified in another PathRule in UrlPathMap /subscriptions/bf287ccd-441f-4ca4-b3f4-45263e5be385/resourceGroups/aks-rtb-dev/providers/Microsoft.Network/applicationGateways/applicationgateway20bd/urlPathMaps/url-e1903c8aa3446b7b3207aec6d6ecba8a." Details=[]
E0114 18:26:28.961820       1 worker.go:62] Error processing event.network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPathsWithinUrlPathMapMustBeUnique" Message="Paths specified in a UrlPathMap must be unique. Path /ms-everquotebid/* is already specified in another PathRule in UrlPathMap /subscriptions/bf287ccd-441f-4ca4-b3f4-45263e5be385/resourceGroups/aks-rtb-dev/providers/Microsoft.Network/applicationGateways/applicationgateway20bd/urlPathMaps/url-e1903c8aa3446b7b3207aec6d6ecba8a." Details=[]
I0114 18:26:35.061298       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0114 18:26:35.271398       1 mutate_app_gateway.go:183] END AppGateway deployment
E0114 18:26:35.271513       1 controller.go:141] network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPathsWithinUrlPathMapMustBeUnique" Message="Paths specified in a UrlPathMap must be unique. Path /ms-everquotebid/* is already specified in another PathRule in UrlPathMap /subscriptions/bf287ccd-441f-4ca4-b3f4-45263e5be385/resourceGroups/aks-rtb-dev/providers/Microsoft.Network/applicationGateways/applicationgateway20bd/urlPathMaps/url-e1903c8aa3446b7b3207aec6d6ecba8a." Details=[]
E0114 18:26:35.271539       1 worker.go:62] Error processing event.network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayPathsWithinUrlPathMapMustBeUnique" Message="Paths specified in a UrlPathMap must be unique. Path /ms-everquotebid/* is already specified in another PathRule in UrlPathMap /subscriptions/bf287ccd-441f-4ca4-b3f4-45263e5be385/resourceGroups/aks-rtb-dev/providers/Microsoft.Network/applicationGateways/applicationgateway20bd/urlPathMaps/url-e1903c8aa3446b7b3207aec6d6ecba8a." Details=[]

**Comment by mortenlerudjordet** [comment]
I dont think there should be a '-' infront of backend.
At least I do not have this in a working deployment.

```
  rules:
    - host: MyHostName
      http:
        paths:
          - path: /
            backend:
              serviceName: MyServiceName
              servicePort: 443
```
