### ISSUE TITLE
No hostname appearing in mutated App Gateway config

### ISSUE THREAD

**Issue by jsouthgate538** [Azure/application-gateway-kubernetes-ingress#1128]
Subscription ID for AKS cluster: 365b1450-afee-4de6-a5ee-db70bb20634a
Subscription ID for Application Gateway. 365b1450-afee-4de6-a5ee-db70bb20634a
AKS cluster name/ARM Resource ID./subscriptions/365b1450-afee-4de6-a5ee-db70bb20634a/resourceGroups/rg-tsadsref/providers/Microsoft.ContainerService/managedClusters/aks-tsadsref
Application Gateway name/ARM Resource ID: /subscriptions/365b1450-afee-4de6-a5ee-db70bb20634a/resourceGroups/rg-tsadsref/providers/Microsoft.Network/applicationGateways/agw-tsadsref

Ingress resource definition that might causing the problem:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: azure/application-gateway
  name: reference-service
spec: 
  rules: 
    - host: thisisourhostname.net
      http: 
        paths: 
          - backend: 
              serviceName: reference-service-helm-deployment
              servicePort: 80
            path: /

```
The Helm configuration used to install the ingress controller:

```
                # This file contains the essential configs for the ingress controller helm chart
                
                # Verbosity level of the App Gateway Ingress Controller
                verbosityLevel: 5

                ################################################################################
                # Specify which application gateway the ingress controller will manage
                #
                appgw:
                  subscriptionId: "365b1450-afee-4de6-a5ee-db70bb20634a"
                  resourceGroup: "rg-tsadsref"
                  name: "agw-tsadsref"
                  usePrivateIP: false

                  # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
                  # This prohibits AGIC from applying config for any host/path.
                  # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
                  shared: true

                ################################################################################
                # Specify which kubernetes namespace the ingress controller will watch
                # Default value is "default"
                # Leaving this variable out or setting it to blank or empty string would
                # result in Ingress Controller observing all acessible namespaces.
                #
                # kubernetes:
                #   watchNamespace: <namespace>

                ################################################################################
                # Specify the authentication with Azure Resource Manager
                #
                # Two authentication methods are available:
                # - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
                armAuth:
                  type: aadPodIdentity
                  identityResourceID: "/subscriptions/365b1450-afee-4de6-a5ee-db70bb20634a/resourcegroups/MC_rg-tsadsref_aks-tsadsref_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msi-aks-tsadsref"
                  identityClientID:  "a5b9a51d-c76a-4ef0-b299-4e5d59923228"

                ## Alternatively you can use Service Principal credentials
                # armAuth:
                #    type: servicePrincipal
                #    secretJSON: <<Generate this value with: "az ad sp create-for-rbac --subscription <subscription-uuid> --sdk-auth | base64 -w0" >>

                ################################################################################
                # Specify if the cluster is RBAC enabled or not
                rbac:
                  enabled: true # true/false

                # Specify aks cluster related information. THIS IS BEING DEPRECATED.
                aksClusterConfiguration:
                  apiServerAddress: "https://k8stsadsref-5b3df5e3.hcp.westeurope.azmk8s.io:443"
```

Checking the logs, the hostname "thisisourhostname.net" is not appearing in the mutated App Gateway config
