### ISSUE TITLE
Expose loadbalancer type service behind application gateway

### ISSUE THREAD

**Issue by prateekchawla** [Azure/application-gateway-kubernetes-ingress#1129]
**Describe the bug**
Not exactly a bug, 

**To Reproduce**
I have two microservices exposed for machine learning models using "az ml model deploy". The attach compute aks command creates a load balancer service azure-ml-fe. I need to get them behind a gateway using ingress.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress-ml
  namespace: azureml-rtb-machine-learning-dev-ws
  annotations:
    # Service are serving content in this path.
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: aks-main-httpsvaultCert
spec:
  rules:
  - host: aks-agw.dev-abc.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: everquotemain
          servicePort: 80
      - path: /*
        backend:
          serviceName: everquotet1
          servicePort: 80
```
**Ingress Controller details**

> Name:             backend-ingress-ml
> Namespace:        azureml-rtb-machine-learning-dev-ws
> Address:          20.**.***.16
> Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
> Rules:
>   Host                      Path  Backends
>   ----                      ----  --------
>   aks-agw.dev-elephant.com
>                             /*   everquotemain:80 (10.0.0.105:5001)
>                             /*   everquotet1:80 (10.0.0.102:5001)
> Annotations:                appgw.ingress.kubernetes.io/appgw-ssl-certificate: aks-main-httpsvaultCert
>                             appgw.ingress.kubernetes.io/backend-path-prefix: /
>                             appgw.ingress.kubernetes.io/ssl-redirect: true
>                             kubernetes.io/ingress.class: azure/application-gateway
> Events:                     <none>

The two nodeport type service
![image](https://user-images.githubusercontent.com/11257391/106941528-f8898380-6748-11eb-9f28-7947c61ef917.png)

Its associated loadbalancer which exposed in scoring URI
![image](https://user-images.githubusercontent.com/11257391/106941128-6c775c00-6748-11eb-9f7a-049ea1c8d5a3.png)
