### ISSUE TITLE
Does the Ingress controller support named-ports?

### ISSUE THREAD

**Issue by javsalgar** [Azure/application-gateway-kubernetes-ingress#1139]
**Is your feature request related to a problem? Please describe.**

We received issues from user saying that the this Ingress rule would not work with AGW Ingress

```
# Source: wordpress/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-wordpress
  labels:
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-10.6.3
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  rules:
    - host: "wordpress.local"
      http:
        paths:
          - path: /
            backend:
              serviceName: RELEASE-NAME-wordpress
              servicePort: http
```

As you can see, the service port is the name of the service port, instead of a number

```
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-wordpress
  labels:
    app.kubernetes.io/name: wordpress
    helm.sh/chart: wordpress-10.6.3
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: RELEASE-NAME
```

This works with other Ingress Controllers, could you confirm if this works too in AGW Ingress?

**Describe the solution you'd like**
