### ISSUE TITLE
SSL redirect not working

### ISSUE THREAD

**Issue by qledelas** [Azure/application-gateway-kubernetes-ingress#1146]
**Describe the bug**
My helm ingress objects are configure with annotations appgw-ssl-certificate and ssl-redirect. The certificate work fine, but not the ssl redirection. 

**To Reproduce**
I have mutliple ingress deploy on a AKS cluster kubernetes version : 1.19.7, Agic version 1.3.0-rc1

This my ingress object after a helm dry-run :
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myWebApp
  labels:
    helm.sh/chart: myWebApp-0.1.0
    app.kubernetes.io/name: myWebApp
    app.kubernetes.io/instance: myWebApp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: ssl-cert-int
spec:
  rules:
    - host: mywebapp.integ.cned.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myWebApp
                port:
                  number: 8000
```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . 
```
Name:         ingress-azure-789f47f9d7-nkx5g
Namespace:    default
Priority:     0
Node:         aks-agentpool-31584682-vmss000000/10.4.0.4
Start Time:   Wed, 17 Feb 2021 17:19:43 +0100
Labels:       app=ingress-azure
              pod-template-hash=789f47f9d7
              release=ingress-azure
Annotations:  checksum/config: 1278c0363d1b7ce9110462738cfdc82e2f22f3b840f7ffcae74eda823f90df04
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.4.0.34
IPs:
  IP:           10.4.0.34
Controlled By:  ReplicaSet/ingress-azure-789f47f9d7
Containers:
  ingress-azure:
    Container ID:   containerd://92e810834a7b3c24d04119f448a49d6aca1c229f16a9edcacc9b825e6d82c021
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.3.0-rc1
    Image ID:       mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:f9f34bb63da1f6df947c535191d00c9a12614738310b71b7baae48440320cc67
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 17 Feb 2021 17:19:51 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-789f47f9d7-nkx5g (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
      AZURE_AUTH_LOCATION:            /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /etc/appgw/ from azure (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-mmskt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/
    HostPathType:  Directory
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  ingress-azure-token-mmskt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-mmskt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
```
* Output of `kubectl logs <ingress controller>. 
```
I0221 23:08:00.624571       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0221 23:08:51.420152       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0221 23:08:51.420177       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0221 23:08:51.424066       1 mutate_app_gateway.go:204] END AppGateway deployment
I0221 23:08:51.424092       1 controller.go:151] Completed last event loop run in: 50.987078443s
I0221 23:08:52.581128       1 redirects.go:44] Created redirection configuration sslr-fl-17ec3f55990c3be9939cc487a4c79b2c for ([mywebapp2.integ.cned.fr    ],443); not yet linked to a routing rule
I0221 23:08:52.581141       1 redirects.go:44] Created redirection configuration sslr-fl-01a7cbd7c61462db77c6202c3292eca8 for ([mywebapp.integ.cned.fr    ],443); not yet linked to a routing rule
I0221 23:08:52.602660       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0221 23:09:43.368248       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0221 23:09:43.368285       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0221 23:09:43.373236       1 mutate_app_gateway.go:204] END AppGateway deployment
I0221 23:09:43.373261       1 controller.go:151] Completed last event loop run in: 50.949045553s
```
* Any Azure support tickets associated with this issue.
I haven't create an Azure support tickets.

I don't understand why I get "not yet linked to a routing rule" for my redirection. 
Thanks for you help.
