### ISSUE TITLE
Configure end to end ssl using key vault certificates.

### ISSUE THREAD

**Issue by manvkaur** [Azure/application-gateway-kubernetes-ingress#1156]
Hi Team,

How can I deploy my applications with end to end ssl enabled using a well known CA certificate stored in a key vault.
AKS:
1. multiple namespaces
2. private cluster
3. CNI enabled
4. AGIC added

Option 1: I see two documents one for [adding ssl cert to agic](https://azure.github.io/application-gateway-kubernetes-ingress/features/appgw-ssl-certificate/) .

Option 2: another one [enabling e2e ssl using self signed cert](https://azure.github.io/application-gateway-kubernetes-ingress/tutorials/tutorial.e2e-ssl/) (not preferred) as we want to store the cert in key vault only and have AKS access the vault for it.

Can you please help on how can I extend Option 1 to enable end to end ssl for AKS cluster with the specs shared

**Comment by akshaysngupta** [comment]
@manvkaur You can use key vault to configure the frontend certificate on Application Gateway. `appgw.ingress.kubernetes.io/appgw-ssl-certificate` allows you refer a certificate that has already been added to the Application Gateway through Portal/CLI/PowerShell.
Please follow this section in the [document](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/appgw-ssl-certificate.md#configure-certificate-from-key-vault-to-appgw) to be able to add a certificate to KeyVault and reference it in the Application Gateway. Then it uses the `appgw.ingress.kubernetes.io/appgw-ssl-certificate` annotation to use with the ingress.

For backend server certificate, you should follow the E2E document but replace the unsigned certificate with your signed certificate.

Please let me know if you need more clarification.

**Comment by manvkaur** [comment]
@

> @manvkaur You can use key vault to configure the frontend certificate on Application Gateway. `appgw.ingress.kubernetes.io/appgw-ssl-certificate` allows you refer a certificate that has already been added to the Application Gateway through Portal/CLI/PowerShell.
> Please follow this section in the [document](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/appgw-ssl-certificate.md#configure-certificate-from-key-vault-to-appgw) to be able to add a certificate to KeyVault and reference it in the Application Gateway. Then it uses the `appgw.ingress.kubernetes.io/appgw-ssl-certificate` annotation to use with the ingress.
> 
> For backend server certificate, you should follow the E2E document but replace the unsigned certificate with your signed certificate.
> 
> Please let me know if you need more clarification.

@akshaysngupta ,
I am able to make the agic listener work on 443 by adding certificate to the agic from the document you have just shared.

I don't have complete clarity on how can I make the cluster IPs work on 443 by using well known CA certs.
Also, my apps have two different namespace:
Sharing sample ingress.yaml below

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-server-service
  namespace: test-ag
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/hello"
    appgw.ingress.kubernetes.io/request-timeout: 60
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: mykeyvaultcert
    appgw.ingress.kubernetes.io/backend-protocol: "https"
spec:
  rules:
  - host: "www.contoso.com"
    http:
      paths:
      - path: /hello/
        backend:
          serviceName: go-server-service
          servicePort: 443
    appgw.ingress.kubernetes.io/backend-protocol: "https"
```
