### ISSUE TITLE
Add health probe protocol annotation

### ISSUE THREAD

**Issue by MartinAbadie** [Azure/application-gateway-kubernetes-ingress#1216]
Hi,

## Issue
I would like expose my app on port 8443 with **HTTPS** protocol for public enpoints, and expose on port 8080 with **HTTP** protocol only for health probes endpoints.
Unfortunatly, if I specify `appgw.ingress.kubernetes.io/backend-protocol: "https"` and `appgw.ingress.kubernetes.io/health-probe-port: "8080"` annotations, created health probes rule uses **HTTPS** on port 8080.

## Solution
It could be usefull to be able to specify health probe protocol with this kind annotation : `appgw.ingress.kubernetes.io/health-probe-protocol: "http"`.

## Attachments
Liveness and readiness example :
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: my-api
  name: my-api
...
          ports:
            - containerPort: 8443
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
...
```

Ingress manifest example :
```yaml
# Statefulset extract
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: my-api
  namespace: my-api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "my-api-tls"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "my-api-ca"
    appgw.ingress.kubernetes.io/backend-hostname: "my-api.com"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/health-probe-port: "8080"
    appgw.ingress.kubernetes.io/health-probe-protocol: "http" # Solution
    appgw.ingress.kubernetes.io/request-timeout: "60"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
...
```

Thanks !

Regards

**Comment by fatpowaranga** [comment]
I believe a workaround at least for the time being if you haven't tried it would be to not specify any health probe via annotations, and instead let it use your readiness probe settings to define the health probe. That is what we are doing currently. (Apologies if I misunderstand)

**Comment by neilkuantm** [comment]
any update about this??
I meet the same issue.
use [`caddy server`](https://github.com/caddyserver/caddy) in the backend pool.

- `caddy deployment` 
```yaml
        ports:
        - containerPort: 80 #redirect to https port.
          name: http
          protocol: TCP
        - containerPort: 443 #service port. 
          name: https
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        - containerPort: 9500 #metrics port
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8003 #health check ready port.
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
```

- `ingress-config`
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "https"
spec:
  tls:
    - hosts:
      - "web.com"
      secretName: "https-certificates"
  rules:
  - host: "web.com"
    http:
      paths:
      - path: /*
        backend:
          service:
            name: web
            port:
              number: 443
        pathType: Prefix
```

But `AGIC` help me to created the health probes use `HTTPS` protocol, it will let backend health check fail...
![image](https://user-images.githubusercontent.com/98370258/163771719-634bf011-5804-4341-95bc-6430061f3d70.png)

Because `caddy server` use `HTTP 8003` to check health check...
![image](https://user-images.githubusercontent.com/98370258/163771835-da6bf8a8-2daf-4e58-bb41-e6eaca84d4b0.png)
  
hi  @akshaysngupta  ,any idea about this ?! 
Thanks you~~~
