### ISSUE TITLE
Wildcard shouldn't be required when using pathType Prefix 

### ISSUE THREAD

**Issue by bchess** [Azure/application-gateway-kubernetes-ingress#1238]
**Describe the bug**
Currently, the Application Gateway Ingress controller require that you include a wildcard `*` at the end of a path for it to serve subpaths, even if `pathType` is set to `Prefix`.

Ingresses that use `pathType: Prefix` shouldn't require the wildcard `*` to be specified in the `path` field of the `HTTPIngressPath`. It's redundant with `Prefix`, and [doesn't line up with the docs](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) or spec. It's not required in other Ingress controllers such the nginx-ingress-controller.

**To Reproduce**
The below Ingress, modified from [ingress-complex.yaml](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/c40f80567d9372b10d2706c9c57208f8742091bc/pkg/tests/ingress-complex.yaml), should serve a request for `/store/foo`. However, it only does so if you change path to `path: /store/*`

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefix-example
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: www.contoso.com
      http:
        paths:
          - path: /store
            backend:
              service:
                name: web-service
                port:
                  number: 80
            pathType: Prefix
```
