### ISSUE TITLE
What's a proper way to manage ssl certificates in app gw?

### ISSUE THREAD

**Issue by rlevchenko** [Azure/application-gateway-kubernetes-ingress#1239]
**Describe the bug**

I'm trying to update a ssl certificate by using this:

```
az network application-gateway ssl-cert update `
  --resource-group <rg name> `
  --gateway-name <gw name> `
  -n <name here> `
  --cert-file <path to pfx file> `
  --cert-password <password here>
```

and getting the following error:

> Two Http Listeners of Application Gateway are using the same Frontend Port

- IDs of those two listeners belong to HTTP listeners (used for SSL Redirection actually)
- HTTP and HTTPS listeners are all managed by ingress. 
- All listeners are using a private frontend ip, 
- Public frontend ip is enabled, no listeners associated to this ip
- All listeners use the app gw certificate (not a cert in k8s or somewhere else).

Possible workarounds:

- delete applications, update the cert, do a new release
- /upload a cert with a new name, update helm templates, do a new release/ just tried and no luck :)

What's the best solution in this case? Can we just update an existing certificate without extra actions?

**Ingress Controller details**

Ingress 1.4.0
Application Gateway in a private mode
k8s 1.19.11, private cluster

**Comment by fatpowaranga** [comment]
I am unsure on what is best practice, however the way I do it is to create a TLS secret resource in the same namespace as the ingress. Here's what a sample YAML might look like:

Ingress.yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
  - hosts: 
    - website.com
    secretName: website-tls-secret
  rules:
  - host: website.com
    http:
      paths:
        - path: /
          pathType: Exact
          backend:
            service:
              name: website-service
              port:
                number: 80
```
Then you just create a TLS secret however you would like, making sure the name is the same as secretName and the namespace is the same as where your ingress is located. AGIC should automagically figure the rest out, though, YMMV.

I hope this helps :)
