### ISSUE TITLE
AGIC pod resource quota settings are missed in Helm repository

### ISSUE THREAD

**Issue by serhiichernukha** [Azure/application-gateway-kubernetes-ingress#1243]
**Description**
As per a merged [PR](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/1169), it's possible to configure pod resource requests and limits. However, there is not in the [Helm repo](https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/). 

**To Reproduce**
Deploy latest Helm chart version using the values containing the following:

```yaml
kubernetes:
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
```

Revise an output of `kubectl describe pod <ingress controller>`
