### ISSUE TITLE
AGIC does not handle comma separated paths correctly.

### ISSUE THREAD

**Issue by askew** [Azure/application-gateway-kubernetes-ingress#1254]
If you have an ingress defined like:
```Yaml
spec:
  rules:
  - http:
      paths:
      - path: /api/*,/swagger/*
        pathType: Prefix
        backend:
          service:
            name: my-api-service
            port:
              name: http
```
then AGIC will create a path map that looks like:
```Json
                    "pathRules": [
                        {
                            "id": "/subscriptions/...",
                            "name": "pr-myapp-rule-0-path-0",
                            "properties": {
                                "backendAddressPool": {
                                    "id": "/subscriptions/..."
                                },
                                "backendHttpSettings": {
                                    "id": "/subscriptions/..."
                                },
                                "paths": [
                                    "/api/*,/swagger/*"
                                ]
                            }
                        }
                    ]

```
This is invalid, and although the Application Gateway accepts the configuration it won't work.

The path map should have the paths separated into an array like
```Json
                                "paths": [
                                    "/api/*",
                                    "/swagger/*"
                                ]
```

**Comment by akshaysngupta** [comment]
@askew Looking at the Ingress API `path` definition/RFC and examples, I don't see that `Path` intended to have comma separated values.
![image](https://user-images.githubusercontent.com/5294363/131889883-befb868b-0af4-4058-a925-be10b3b68210.png)
Link to RFC: https://datatracker.ietf.org/doc/html/rfc3986/#section-3.3

Obviously, you can specify as follows as well:
```yaml
- path: /api/*
   pathType: Prefix
   backend:
     service:
       name: my-api-service
       port:
         name: http
- path: /swagger/*
   pathType: Prefix
   backend:
     service:
       name: my-api-service
       port:
         name: http
```
