### ISSUE TITLE
Enable priority configuration for listeners

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/application-gateway-kubernetes-ingress#1268]
**Is your feature request related to a problem? Please describe.**
When creating multiple listeners using wildcards with AGIC, as example:
- *.contoso.com
- b2b.contoso.com
I would like that the second one have more priority than the wildcard domain, to establish a esspecific configuration for this ingress. Currently, the evaluation order depends of which ingress has been configured before, so is practically random. I would like to be able to specify a priority (see https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview#request-routing-rules-evaluation-order) to ensure that the more specific ingress works properly. 

**Describe the solution you'd like**
I think that we could use an annotation like `appgw.ingress.kubernetes.io/listener-priority: "1"`, to be able to set the priority to the listener created by AGIC.

**Comment by thisispaulsmith** [comment]
Something like this is needed urgently. Path based routing is random. Example path based routing app/* app/testing will match which ever is defined first in AGW which you have no control over atm.

**Comment by nvenkatapavan** [comment]
This feature is very much required, We are facing issues when we use wild cards in ingress. AGIC randomly assigns priority causing all issues. Any ETA on this issue please ?

**Comment by LeartBeqiraj** [comment]
TEMPORARY WORKAROUND: I am using this bash script to update rule's priority every 5 seconds. I am increasing the value number of priority that is attached with the rule (*.contoso.com) so this will be always processed last:

 
```
#!/bin/bash

while true
do
echo "I'm running now"

az network application-gateway rule show -g {resource_group} --gateway-name {gateway_name} -n {rule_name} > priority.json
cat priority.json | grep 19090 >> /dev/null
status=$?

  if [ $status -ne 0 ]
  then
    az network application-gateway rule update -g MC_klp-vnet-rg_klp-cluster_eastus --gateway-name {gateway_name} -n {rule_name} --priority {19090}
    echo "---------------"
    echo "priority configured to 19090"
    echo "I'm sleeping now"
    echo "---------------"
  elif [ $status -eq 0 ]
  then
    echo "priority is already 19090"
    echo "I'm sleeping now"
    echo "---------------"
  fi
sleep 5
done
```

**Comment by tabare-patino** [comment]
Any updates? I'm experiencing the exact same issue. 

The behavior is really strange, for example:

```
spec:
  rules:
  - host: "media.contoso.com"
    http:
      paths:
      - backend:
          service:
            name: media-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: "*.contoso.com"
    http:
      paths:
      - backend:
          service:
            name: web-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

When I use media.contoso.com I access the web-service. It doesn't respect the order, it doesn't even matter if I divide into two different ingress resources. 

However, the funny part is that when I change the subdomain to:

```
spec:
  rules:
  - host: "filemanager.contoso.com"
    http:
      paths:
      - backend:
          service:
            name: media-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  - host: "*.contoso.com"
    http:
      paths:
      - backend:
          service:
            name: web-service
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

With the change of the sub-domain to filemanager.contoso.com I'm able to load the media-service now.

I can't understand the behavior or the order that is chosen for the listeners. 

Thanks.
