### ISSUE TITLE
Ingress path rules with pathType: Prefix aren't rendered as wildcard rules.

### ISSUE THREAD

**Issue by brainpad-koizumi** [Azure/application-gateway-kubernetes-ingress#1279]
https://v1-19.docs.kubernetes.io/docs/concepts/services-networking/ingress/#path-types

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-management-app
  namespace: app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: "/prefix/"
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 8080
```

When a path rule has a `pathType` specified and set to `Prefix`, then the path rule needs to be rendered with `/*` appended to it so that the any request whose URI contains the path as a prefix will match to the rule, but it actually is rendered as if the pathType was set to `Exact`:

```
{
    "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/XXX/providers/Microsoft.Network/applicationGateways/XXXXXX/urlPathMaps/url-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/pathRules/pr-app-ingress-management-app-rule-0-path-0",
    "name": "pr-app-ingress-management-app-rule-0-path-0",
    "properties": {
        "backendAddressPool": {
            "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/XXX/providers/Microsoft.Network/applicationGateways/XXXXXX/backendAddressPools/pool-app-app-web-8080-bp-8080"
        },
        "backendHttpSettings": {
            "id": "/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/XXX/providers/Microsoft.Network/applicationGateways/XXXXXX/backendHttpSettingsCollection/bp-app-app-web-8080-8080-ingress-management-app"
        },
        "paths": [
            "/prefix"
        ]
    }
}
```

Where the `paths` part should have been:
```
        "paths": [
            "/prefix/*"
        ]
```
