### ISSUE TITLE
App Gateway Probes isn't configured according to readiness/liveness probes

### ISSUE THREAD

**Issue by ahilmathew** [Azure/application-gateway-kubernetes-ingress#1285]
**Describe the bug**

The Application Gateway Ingress Controller documentation says that if `liveness`/`readiness` probes are included in the pod/deployment spec, then those values are used by the controller to configure `Health Probes` for the Application Gateway.
But it doesn't seem to happen in our case.
**To Reproduce**
Ingress Annotations:
```
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: dev-ssl-cert
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    external-dns.alpha.kubernetes.io/ttl: "60"
    kubernetes.io/ingress.class: azure/application-gateway
```

Deployment Spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-api
  namespace:example-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example-api
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: example-api
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: example-api-cm
        - secretRef:
            name: example-api-sc
        image: example-api:15
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "90"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8089
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: example-api
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8089
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

Am I missing any annotations? What am I configuring wrong here? Would be great to get an answer ASAP.
Thank you!
