### ISSUE TITLE
AGIC 1.5.0 doesn't resolve port names correctly

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/application-gateway-kubernetes-ingress#1318]
**Describe the bug**
AGIC isn't resolving ports correctly when are identified by name. The error is the following:
```
E0105 12:15:57.954573       1 backendhttpsettings.go:85] Code="ErrorServiceResolvedToInvalidPort" Message="service xxx/xxx and service port http was resolved to an invalid service-backend port 65536, defaulting to port 80"
```

**To Reproduce**
Use AKS 1.22 and AGIC 1.5.0-rc1
Create an ingress like this
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  name: xxx
spec:
  rules:
  - host: xxx
    http:
      paths:
      - backend:
          service:
            name: xxx
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - secretName: xxx
```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by sunnvsp** [comment]
Hi, I think you have to change the configuration a little bit.

from

```
  rules:
  - host: xxx
    http:
      paths:
      - backend:
          service:
            name: xxx
            port:
              name: http
        path: /
        pathType: Prefix
```

to

```
rules:
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: xxx
                port:
                   name: http
```
