### ISSUE TITLE
If secret is not found then service is accessible via http

### ISSUE THREAD

**Issue by rkoplinger** [Azure/application-gateway-kubernetes-ingress#1326]
**Describe the bug**
If you create an ingress resource with spec.tls defined and secret which is referenced in spec.tls[].secretName does not exist yet, then AGIC will create a rule on http listener. After some time when the secret is created, the rule is moved to https listener. During this time window, the service is accessible via http. The desired behavior is that AGIC waits until the secret is created and only then creates a rule on the https listener.

**To Reproduce**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  name: test
spec:
  rules:
  - host: test
    http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 5000
        path: /*
        pathType: Prefix
  tls:
  - hosts:
    - test
    secretName: test
```

**Ingress Controller details**
Controller Version 1.4.0
