### ISSUE TITLE
WAF listener policies get dropped (Listener configs erroneously overwritten when multiple ingresses are present for the same host)

### ISSUE THREAD

**Issue by rbitanga-manticore** [Azure/application-gateway-kubernetes-ingress#1365]
**Describe the bug**
If multiple ingress objects with differing annotations exist for the same host, the configuration from the last encountered ingress object will overwrite the configuration from the previous ingresses instead of merging them. 

As an example, WAF policies that are supposed to be applied to a listener do not get applied if a subsequent ingress with a name that causes it to be sorted later is present.

This is because a new listener config object is always created when `processIngressRuleWithTLS` is invoked in https://github.com/Azure/application-gateway-kubernetes-ingress/blob/8242b5613caa1e8232f1df69a968ec31f359f3b5/pkg/appgw/ingress_rules.go#L62

**To Reproduce**
Given
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/waf-policy-for-path: <policy1>
  name: ingress-a
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name: service-a
            port:
              number: 80
        path: /*
        pathType: ImplementationSpecific
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/waf-policy-for-path: <policy2>
  name: ingress-z
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name: service-b
            port:
              number: 80
        path: /foobar
        pathType: ImplementationSpecific
```
`FirewallPolicy` will not be set on the listener associated with host `<host>` because sorting by name guarantees that `ingress-z` gets processed after `ingress-a`. 

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```
Containers:
  ingress-azure:
    Container ID:   containerd://6c292665be674834347c560c2b4c24937abdf9ce809777ced115929736fda7a9
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.5.0
    Image ID:       mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:d3f2df83ef3e93acbd127208fcca607dbf825fa90a75de7e218aa05960555c97
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 16 Mar 2022 15:33:46 +0800
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      kube-system-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  kube-system-ingress-azure-69d845c5c-lrmjs (v1:metadata.name)
      AGIC_POD_NAMESPACE:             kube-system (v1:metadata.namespace)
    Mounts:
      /etc/appgw/ from azure (ro)
```
* Output of `kubectl logs <ingress controller>. 
```
I0316 07:58:59.357272 1 ingress_rules.go:41] Attach WAF policy: <policy> to listener: fl-56c96bb38b015f7a395426ef9c97e233
```
```
-- App Gwy config -- {
-- App Gwy config -- "id": "<redacted>/httpListeners/fl-56c96bb38b015f7a395426ef9c97e233",
-- App Gwy config -- "name": "fl-56c96bb38b015f7a395426ef9c97e233",
-- App Gwy config -- "properties": {
-- App Gwy config -- "frontendIPConfiguration": {
-- App Gwy config -- "id": "<redacted>/frontendIPConfigurations/appGatewayFrontendIP"
-- App Gwy config -- },
-- App Gwy config -- "frontendPort": {
-- App Gwy config -- "id": "<redacted>/frontendPorts/appGatewayFrontendPort"
-- App Gwy config -- },
-- App Gwy config -- "hostNames": [
-- App Gwy config -- "<host>"
-- App Gwy config -- ],
```

Note the missing:
```
-- App Gwy config -- "firewallPolicy": {
-- App Gwy config -- "id": "<policy1>"
-- App Gwy config -- },
```
