### ISSUE TITLE
Annotation "rewrite-rule-set" is not working 

### ISSUE THREAD

**Issue by Digindataflow** [Azure/application-gateway-kubernetes-ingress#1396]
**Describe the bug**
application gateway has one path based routing rule with two paths. 
Annotation "rewrite-rule-set" is set to existing rewrite rule set. 
However, after each deployment, the rewrite rule set is not checked for both paths.

**To Reproduce**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: name1
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/rewrite-rule-set: rewrite-rule-set-1
spec:
  rules:
    - host: host.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service1
              port:
                number: 80
        - path: /path/*
          pathType: Prefix
          backend:
            service:
              name: service2
              port:
                number: 80
```
