### ISSUE TITLE
AGIC Reverting to defaulthttp probe suddenly

### ISSUE THREAD

**Issue by jayendranarumugam** [Azure/application-gateway-kubernetes-ingress#1411]
**Describe the bug**

_New to AGIC and Kubernetes :)_

AGIC reverting the `backend setting` of the ingress to defulthttp healthprobe automatically

The ingress will create the custom healthprobe correctly. It also assign the backendsetting to correct custom healthprobe but suddenly it is reverting to defaulthttp probe

Azure Support Raised : 2207070030001005

**Ingress Controller details**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: cert-04212022
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/backend-protocol: http
    appgw.ingress.kubernetes.io/health-probe-hostname: http://testapi-api.demo.com
    appgw.ingress.kubernetes.io/health-probe-interval: "45"
    appgw.ingress.kubernetes.io/health-probe-path: /apihealthcheck
    appgw.ingress.kubernetes.io/health-probe-port: "5000"
    appgw.ingress.kubernetes.io/request-timeout: "90"
    appgw.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: azure/application-gateway
    meta.helm.sh/release-name: helm-release1
    meta.helm.sh/release-namespace: test-namespace
spec:
 defaultBackend:
    service:
      name: my-service
      port:
        number: 443
  rules:
    - host: http://testapi-api.demo.com
      http:
        paths:
        - backend:
            service:
              name: my-service
              port:
                number: 443
          path: /api
          pathType: Prefix
 ```
   

All the other details where already given on the support ticket.
