### ISSUE TITLE
Path annotation that allows multiple paths.

### ISSUE THREAD

**Issue by eduardodfmex** [Azure/application-gateway-kubernetes-ingress#1416]
**Is your feature request related to a problem? Please describe.**

AGIC limitation required we create one ingress for each API paths available in our Microservices.  

- Language: Java 11.0.2 with Spring Boot 2.5.6

- Application Gateway Ingress Controller: version 1.0

- Helm: version 2

- AKS with Kubenet network

- Custom IP routing table

Path annotation don't work with multiple path's [link](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#backend-path-prefix).

We need to create two (2) ingresses instead of just create two path rules.

**Describe the solution you'd like**

Ask: path annotation that allows multiple paths providing a seamless approach used by other ingress controllers (i.e. Nginx)

In the example below we need to create two (2) ingresses instead of just create two path rules. 

```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "microservice.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
# Ingress for "/microservice/path#"
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-microservice1
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    appgw.ingress.kubernetes.io/backend-path-prefix: "/microservice/path001"
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: microservice
            port:
              number: 8082
        path: /microservice/path001
        pathType: Prefix
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-microservice2
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    appgw.ingress.kubernetes.io/backend-path-prefix: "/microservice2/path002"
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: microservice2
            port:
              number: 8082
        path: /microservice2/path002
        pathType: Prefix
  {{- end }}

```
For a sample on the path annotation see this [link](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#backend-path-prefix).

Nginx multiple paths sample [link](https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/#example_1):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress-3
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: test.com
    http:
      paths:
      - path: /foo/bar/bar
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
      - path: /foo/bar/[A-Z0-9]{3}
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```
