### ISSUE TITLE
Please add reconcilePeriodSeconds as an option for cluster add-on

### ISSUE THREAD

**Issue by 03eltond** [Azure/application-gateway-kubernetes-ingress#1446]
Currently, there is an issue where redeploying bicep (probably ARM too?) templates for AG removes the backend configuration set by AGIC (even if nothing has changed):
https://github.com/Azure/bicep/issues/2316

As a workaround, `reconcilePeriodSeconds` can be used to force AGIC to sync to AG:
https://azure.github.io/application-gateway-kubernetes-ingress/features/agic-reconcile/

While this workaround is rather unfortunate due to implied downtime of 30 seconds or more, it is at least a solution. However, this workaround is not available for AGIC when configured as an AKS addon:
https://docs.microsoft.com/en-us/azure/architecture/example-scenario/aks-agic/aks-agic#alternatives

Installing AGIC as a helm chart instead of a cluster addon isn't a deal breaker, but it sure is convenient to take advantage of the declarative nature of defining it as an add-on for our IaC.

Solutions I would prefer, in order:
- Any solution which doesn't cause any down time. This limitation prevents us from deploying during most hours except for the case of emergencies. This could maybe be achieved by allowing the backend configurations to be optional in the bicep templates (see #2316 above), such that there is no sync performed if omitted.
- Just do the reconcile automatically, so I don't have to configure this.
- Expose the `reconcilePeriodSeconds` as something I can configure as an add-on.

**Comment by f-vt** [comment]
Hi,


I've found something in AGIC code [https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/environment/environment.go](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/environment/environment.go)

```
// ReconcilePeriodSecondsVarName is an environment variable to control reconcile period for the AGIC.
ReconcilePeriodSecondsVarName = "RECONCILE_PERIOD_SECONDS"
```


Tried it in my ingress yaml definition :

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-agic
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "MyAppGWCertificateName"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: my.host
    http:
      paths:
      - path: /
        backend:
          service:
            name: myServiceToBeProxied
            port:
              number: 8000
        pathType: Exact
  env:
  - name: RECONCILE_PERIOD_SECONDS
    value: 30
```

Seems working as expected, now every change done on App Gw is remediated very fast by AGIC ingress compared when not setting this environment variable.
