### ISSUE TITLE
Adding AzureApplicationGatewayRewrite creates unwanted extra rule

### ISSUE THREAD

**Issue by MariusGrandeAndersen** [Azure/application-gateway-kubernetes-ingress#1496]
**Describe the bug**
When you add an AzureApplicationGatewayRewrite to the latest helm chart 1.6.0, it automatically adds an unwanted section breaking the rule

**To Reproduce**
using ingress-azure helm chart 1.6.0

Add the following:

```
apiVersion: appgw.ingress.azure.io/v1beta1
kind: AzureApplicationGatewayRewrite
metadata:
  name: x-forwarded-headers
  namespace: istio-system
spec:
  rewriteRules:
    - name: x-forwarded-headers
      ruleSequence: 100
      actions:
        requestHeaderConfigurations:
          - actionType: set
            headerName: X-Forwarded-For
            headerValue: "{var_add_x_forwarded_for_proxy}"
```

on the ingress, add the rewrite header

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "istio-ingressgateway-development"
  namespace: "istio-system"
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/rewrite-rule-set-custom-resource: x-forwarded-headers
```

Expected result:
New rewrite rule is created that looks like this:
![image](https://user-images.githubusercontent.com/3061094/214377168-f4242ceb-ab81-401c-9af9-44045190d865.png)

Current result:
We get some unexpected extra rule breaking the rule:
![image](https://user-images.githubusercontent.com/3061094/214377062-ee40f3a3-1a66-42f2-b894-2ae433a7b4d7.png)
