### ISSUE TITLE
AGIC Helm Chart support Service Principal Kubernetes Secret

### ISSUE THREAD

**Issue by TimDurward** [Azure/application-gateway-kubernetes-ingress#1546]
**Is your feature request related to a problem? Please describe.**
It will be nice to reference an existing secret in Kubernetes, rather than plainly putting the base64 within the values.yaml file. This helps with people that use Git-Ops and utilize controllers like SealedSecrets and store their Secrets in Git. 

**Describe the solution you'd like**

A Kubernetes Secret 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
data:
  credentials.json: <base64-encoded-credentials>
```

Deploying AGIC referencing the secret

```diff
ingress-azure:
  appgw:
    subscriptionId: your-azure-subscription-id
    resourceGroup: your-azure-resource-group
    name: your-application-gateway-name
  armAuth:
    type: servicePrincipal
-   secretJSON: {}
+   existingSecret: azure-credentials
```
