### ISSUE TITLE
appgw.prohibitedTargets does not work with wildcard hostname

### ISSUE THREAD

**Issue by pguyot** [Azure/application-gateway-kubernetes-ingress#1548]
Using a values file with appgw.prohibitedTargets does not work with a wildcard in the hostname.

Typically, the following AzureIngressProhibitedTarget:

```yaml
apiVersion: "appgw.ingress.k8s.io/v1"
kind: AzureIngressProhibitedTarget
metadata:
  name: prohibit-star.domain.com
spec:
  hostname: "*.domain.com"
```

cannot be added with the following values:
```yaml
appgw:
    shared: true
    prohibitedTargets:
    - name: prohibit-star.blueplanner.com
      hostname: "*.domain.com"
```

The following error is generated:
```
Error: YAML parse error on ingress-azure/templates/crds.yaml: error converting YAML to JSON: yaml: line 6: did not find expected alphabetic or numeric character
```
