### ISSUE TITLE
Health check Failing

### ISSUE THREAD

**Issue by caxefaizan** [Azure/application-gateway-kubernetes-ingress#1561]
I Have an application deployed whose service has the following ports
```
apiVersion: v1
kind: Service
metadata:
  name: app-ingress-svc
  namespace: app
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
```
I configured my INgress object as
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigee-ingress
  namespace: apigee
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    appgw.ingress.kubernetes.io/backend-protocol: https
    appgw.ingress.kubernetes.io/health-probe-path: "/healthz/ready"
    appgw.ingress.kubernetes.io/health-probe-port: "15021"
spec:
  tls:
  - hosts:
      - poc-api.gehealthcare.net
  rules:
  - host: poc-api.gehealthcare.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: apigee-ingress-svc
            port:
              number: 443
        pathType: Prefix
```

I have the AGIC add on depployed on my AKS cluster
where the logs suggests
```
I0712 12:49:58.547239       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0712 12:50:05.315625       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0712 12:50:05.315647       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0712 12:50:05.316380       1 mutate_app_gateway.go:204] END AppGateway deployment
I0712 12:50:05.316395       1 controller.go:151] Completed last event loop run in: 6.890477793s
```
However, My health check is failing.
One reason could be that my health check protocol is http. But there is no annotation to support that unlike the AWS-ALB controller, where we can define `alb.ingress.kubernetes.io/healthcheck-protocol: HTTP`

I tried creating a custom probe
![image](https://github.com/Azure/application-gateway-kubernetes-ingress/assets/63395276/acf4ed5c-b58e-4d99-8baf-06947b9c5245)

with the respectibe backend setting as 
![image](https://github.com/Azure/application-gateway-kubernetes-ingress/assets/63395276/3c313d21-1aa8-48c1-86dc-e392477df96e)

but on testing it i get
![image](https://github.com/Azure/application-gateway-kubernetes-ingress/assets/63395276/4d056ba5-c447-4d67-bce5-4d3dbb2803e1)

Am i doing anything wrong here?
