### ISSUE TITLE
Support regex in AzureIngressProhibitedTarget

### ISSUE THREAD

**Issue by birjj** [Azure/application-gateway-kubernetes-ingress#1579]
**Is your feature request related to a problem? Please describe.**
The current implementation of [multi-cluster shared gateway](https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-existing/#multi-cluster-shared-app-gateway) has the (often blocking) problem that it requires _each cluster to know every hostname it should ignore_.  
This often isn't practical to maintain, as evident by the number of different issues here (e.g. #1542, #1517, #1382).

**Describe the solution you'd like**
A few different solutions exists for this (e.g. #1542), but one that is simple to implement would be to support regular expressions in the `hostname` field of AzureIngressProhibitedTarget resources. This would allow far more extendable logic - e.g. "not `prod.*`", "not `specific.example.com`" and similar - to be implemented without requiring new use-case-specific resource definitions.

Specifically, the CRD would need a way to indicate that the hostname is a regex (so `test.example.com` wouldn't match `testxexample.com` if that isn't the intention), and the following line would have to be augmented to use [`regexp.MatchString`](https://pkg.go.dev/regexp#MatchString) if that is the case:

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/91fa7b29b7be7e8e437a75390358d5d905413364/pkg/brownfield/targets.go#L37

**Implementation details**
I'm imagining that we could either use a flag embedded in the hostname (e.g. `hostname: "r:prod\.*"` indicates a regex),

```yaml
kind: AzureIngressProhibitedTarget
metadata:
  name: disable-prod
spec:
  hostname: r:prod\.*
```

or an annotation on the resource similar to [nginx.ingress.kubernetes.io/use-regex](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#use-regex):

```yaml
kind: AzureIngressProhibitedTarget
metadata:
  name: disable-prod
  annotations:
    appgw.ingress.kubernetes.io/use-regex: "true"
spec:
  hostname: prod\.*
```
