### ISSUE TITLE
Unsecure Default TLS Policy because of the AGIC controller using old network API version (< 2023-02-01) and deprecated Azure SDK

### ISSUE THREAD

**Issue by zioproto** [Azure/application-gateway-kubernetes-ingress#1620]
Looking at this line of code:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/8bc1e63c3714667bb59f8533fd39b8970e77bd2b/pkg/azure/client.go#L15

I understand the AGIC controller is using a deprecated Azure SDKs  and should upgraded following this guide: 
https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md

There is an impact on **security**. Because the deprecated Azure SDK consumes an ARM API version lower than `2023-02-01` in the **Default TLS policy** the minimum protocol version is set to **TLS 1.0**

This was originally reported by a customer here:
https://github.com/Azure/terraform-azurerm-aks/issues/532

How this is actionable ?
Please patch the code to use API versions `2023-02-01` or higher, then the minimum TLS protocol version is set to 1.2

Documentation reference:
https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#default-tls-policy

Cc: @chixcancode @JackStromberg

**Comment by ralph-tice** [comment]
In addition to the default here, the workaround of applying the annotation explicitly on the Ingress resource doesn't result in the SSL policy being applied by AGIC:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-all
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/ssl-policy: "AppGwSslPolicy20220101"
```

despite the annotation being visible in the portal:
![image](https://github.com/Azure/application-gateway-kubernetes-ingress/assets/2474730/8919182a-1ce9-43db-b8f8-04d2b2db99e3)
