### ISSUE TITLE
AGIC 1.7.4 provided by AKS doesn't resolve port names correctly

### ISSUE THREAD

**Issue by HujinoKun** [Azure/application-gateway-kubernetes-ingress#1655]
Hello,

**Describe the bug**

AGIC isn't resolving ports correctly when are identified by name. The error is the following :

```
Warning  PortResolutionError  21m (x2 over 21m)  azure/application-gateway  Code="ErrorServiceResolvedToInvalidPort" Message="service keycloak/keycloak and service port http was resolved to an invalid service-backend port 65536, defaulting to port 80"
```

**To Reproduce**

- Use AKS 1.31 and AGIC 1.7.4 provided by aks

**Ingress Controller details**

* Output of `kubectl -n keycloak get ingress keycloak -oyaml` : 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    meta.helm.sh/release-name: keycloak
    meta.helm.sh/release-namespace: keycloak
  creationTimestamp: "2024-10-31T14:14:25Z"
  generation: 1
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.0.4
    helm.sh/chart: keycloak-24.0.3
  name: keycloak
  namespace: keycloak
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: keycloak.domain
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - keycloak.domain
    secretName: keycloak.domain-tls
```
