### ISSUE TITLE
Support for Web Socket

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure/application-gateway-kubernetes-ingress#169]
Does the App Gateway ingress controller support Web Socket traffic?

**Comment by asridharan** [comment]
I believe Application Gateway v2 does support web sockets. @akshaysngupta could you confirm?

@rahulvmarathe  however don't think we expose any specific configurations for web sockets?

**Comment by rahulvmarathe** [comment]
Hi @asridharan, thanks for the update per this https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-websocket, App Gateway does support Web Sockets. 

Wanted to know if there is anything specific I need to for it to work with the AKS Ingress.

**Comment by draychev** [comment]
@rahulvmarathe I tested App Gateway v2 and the K8s Ingress. As expected - App Gwy has native support for websockets.  And I did not have to do anything special to expose my Golang websockets server.

Here is my Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-repeater
spec:
  selector:
    matchLabels:
      app: wsrepeater
  replicas: 2
  template:
    metadata:
      labels:
        app: wsrepeater
    spec:
      containers:
        - name: websocket-repeater
          imagePullPolicy: Always
          image: abc.azurecr.io/websockets-repeater
          ports:
            - containerPort: 8888
      imagePullSecrets:
        - name: acr-creds

---

apiVersion: v1
kind: Service
metadata:
  name: websocket-repeater
spec:
  selector:
    app: wsrepeater
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websocket-repeater
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: ws.mis.li
      http:
        paths:
          - backend:
              serviceName: websocket-repeater
              servicePort: 8888
```

One small caveat though: my particular [websocket server implementation](https://github.com/gorilla/websocket/blob/master/examples/chat/main.go) is fairly strict - requires the `Sec-Websocket-Version` header etc.  So a default Health Check doing an HTTP GET on `/ws` and expecting a `200` did not work.  As a result my pods were marked as unhealthy by App Gateway. Eventually that results in a 502.

Here is what a health ywebsocket call would look like:
```sh
curl -i -N -H "Connection: Upgrade" \
        -H "Upgrade: websocket" \
        -H "Host: localhost" \
        -H "Origin: http://localhost" \
        -H "Sec-Websocket-Version: 13" \
        -H "Sec-WebSocket-Key: 123" \
        http://1.2.3.4:8888/ws
```

So because we don't have a websocket specific health check and my implementation is strict - I had to add an endpoint `/health` just for monitoring.
Another workaround would have been to make custom health probes in App Gwy that accept error code 400, which is what my server returns when the websocket specific headers are missing.

Please reach out if I can further assist you with this.  I'll consider this question answered (and we'll augment our documentation with this blurb here to make it clear that the ingress and app gwy v2 support websocktes)

**Comment by akshaysngupta** [comment]
@draychev We should document this.

**Comment by MarkDNL** [comment]
@draychev @akshaysngupta We have some issues in successfully implementing our websocket enabled application via AGIC and the AppGW. The websocket connection drops after 30 seconds, which is the default http timeout. When changing the timeout vault, the ws connection drops at the selected value. We submitted a ticket at Azure support, but their suggestion was the following:
> The backend should be available to work on both HTTP and HTTPS. I can see that your app gateway backend pool only has port 80 enabled.

But the documentation states that the Listeners must be setup correctly:
> You would need both HTTP and HTTPS listeners to support WebSocket and secure WebSocket traffic.


I find it hard to believe that HTTPS is mandatory for websocket. Your example above here does not use HTTPS, also your example in the documentation on Websocket does not use HTTPS. I hope you can shed a light on the issue we are experiencing.

We tried the following setup:
```
apiVersion: v1
kind: Pod
metadata:
  name: ws
  labels:
    app: ws
spec:
  containers:
    - name: ws
      image: ********.azurecr.io/ws:latest
    - name: nginx
      image: ********.azurecr.io/ws-nginx:latest
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
      - name: cert
        mountPath: "/certs"
        readOnly: true
  volumes:
  - name: cert
    secret:
      secretName: cert-1
---
apiVersion: v1
kind: Service
metadata:
  name: ws
spec:
  selector:
    app: ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ws
  labels:
    app: ws
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: ws.********.tech
    http:
      paths:
      - backend:
          serviceName: ws
          servicePort: 80
      - backend:
          serviceName: ws
          servicePort: 443
  tls:
  - secretName: cert-1
```
This deploys a small NodeJS application, inlcuding and Nginx in front, which exposes 80 and 443, and also loads the SSL certificates.

The `ws` service exposes these two ports. The ingress includes two backend ports: 80 and 443, but this fails at azure-ingress-pod-level:

```
`Processing event failed:network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 – Original Error: Code="ApplicationGatewayPortNotValidForProtocol" Message="Port 443 is not valid for protocol Http in backendHttpSettingsCollection /subscriptions/********-****-****-****-************/resourceGroups/d-weu-rg-shared-dev/providers/Microsoft.Network/applicationGateways/d-app-ag-dev/backendHttpSettingsCollection/bp-default-ws-443-443-ws." Details=[]
```

Removing the `backend` with port 443 works, but still the WS connection drops after 30 sec.

We tested using `npm i -g ws` and store the following script in a file (e.g. `client.js`): 

```
const WebSocket = require('ws');

const ws = new WebSocket('wss://ws.*****.tech', { rejectUnauthorized: false });

ws.on('open', function open() {
  console.log('connected')
});

ws.on('close', function close() {
  console.log('disconnected');
});

```
After running `node client.js` we notice that the connection drops after 30 sec.

Conclusion: Its still unclear whats the issue is, all requirements seem to be fulfilled.

We now ended up using a Keep-Alive ping, which is sent from the server to the client to keep the connection up. But I believe that this should not be necessary.
