### ISSUE TITLE
Helm repository public access prohibited

### ISSUE THREAD

**Issue by niklasjoh** [Azure/application-gateway-kubernetes-ingress#1691]
**Describe the bug**
Once again you have closed down your helm repository for public access, and we now get a 409 when we try to pull the chart.

```failed to fetch Helm repository index: failed to cache index to temporary file: failed to fetch https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/index.yaml : 409 Public access is not permitted on this storage account.```

Error can be seen here: https://appgwingress.blob.core.windows.net/ingress-azure-helm-package

This happened last year - 2024-09 - and it took a few days (!) to clear.
Maybe this time you know what resolved the issue and can make it available again.

I also would want to know WHY and HOW this has happened again!?

**To Reproduce**
Try to deploy helm chart to kubernetes.

Kustomize:
```
helmCharts:
  - name: ingress-azure
    namespace: ingress-appgw
    releaseName: ingress-appgw
    repo: https://appgwingress.blob.core.windows.net/ingress-azure-helm-package
    version: "1.7.2"
```
`kubectl kustomize --enable-helm . | kubectl apply -f -`

**Output**
error: accumulating resources: accumulation err='accumulating resources from 'ingress-appgw': '/home/vsts/work/1/s/infra/ingress-appgw' must resolve to a file': recursed accumulation of path '/home/vsts/work/1/s/infra/ingress-appgw': Error: looks like "[https://appgwingress.blob.core.windows.net/ingress-azure-helm-package"](https://appgwingress.blob.core.windows.net/ingress-azure-helm-package%22) is not a valid chart repository or cannot be reached: failed to fetch https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/index.yaml : 409 Public access is not permitted on this storage account.
