### ISSUE TITLE
Unable to install ingress with helm chart - application-gateway-kubernetes-ingress/ingress-azure

### ISSUE THREAD

**Issue by Prince269090** [Azure/application-gateway-kubernetes-ingress#299]
**Bug Details**

I am trying to configure connection between AKS and Applicaiton Gateway in azure. The error is coming while i try to install the ingress controller using helm install. I have followed all steps in this [link](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/install-existing.md)

**To Reproduce**
To reproduce please follow the steps as mentioned [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/install-existing.md).

The error comes when i try to execute below command.

`helm install -f helm-config.yaml application-gateway-kubernetes-ingress/ingress-azure`

**Error Details**

Error: render error in "ingress-azure/templates/deployment.yaml": template: ingress-azure/templates/deployment.yaml:35:93: executing "ingress-azure/templates/deployment.yaml" at <.Values.aksClusterConfiguration.apiServerAddress>: nil pointer evaluating interface {}.apiServerAddress

**Helm Config**

```
# This file contains the essential configs for the ingress controller helm chart

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: b3e66537-8dff-4a4c-9821-e8cfb992b468
    resourceGroup: multimedia-dev
    name: appgateway-dev

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/b3e66537-8dff-4a4c-9821-e8cfb992b468/resourcegroups/MC_multimedia-dev_kubernetes-dev_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/multimedia-k8s-identity
    identityClientID:  a6a3e405-5f8c-4e15-9f9e-1a0a4f846e77

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
    enabled: true # true/false
```
