### ISSUE TITLE
bad request - path based routing

### ISSUE THREAD

**Issue by mtuppad** [Azure/application-gateway-kubernetes-ingress#355]
(below configuration had worked for couple of times 3-4 months back. But right now its not. I am currently trying this in central india - worked earlier southeast asia) 

I have deployed 2 simple apps into AKS
1. Guestbook - exposed as frontend service at port 80
2. An API App with path /api/values exposed as apiservice at port 80

Can access front app (guestbook) without any issue. 
However when I try to access the api - I get bad gateway error. 
I have tried with path /api/* or /api/values 
also I tried to use appgw.ingress.kubernetes.io/backend-path-prefix: "/" 
But nothing worked. 

Here are my services

kubectl get services
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
apiservice     ClusterIP   10.0.7.142     <none>        80/TCP     23h
frontend       ClusterIP   10.0.70.143    <none>        80/TCP     23h

Output within a pod for the API service. 
```
curl apiservice/api/values
["value1","value2"]

```
when I access from Application gateway URL - I get bad gateway error. 

Here is my ingress yaml. 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: tupakscin.centralindia.cloudapp.azure.com
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: apiservice
          servicePort: 80
      - backend:
          serviceName: frontend
          servicePort: 80

```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

```
Name:               invited-whale-ingress-azure-5d65689dd-vhjjt
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-16978572-1/20.20.0.4
Start Time:         Thu, 04 Jul 2019 12:30:09 +0530
Labels:             aadpodidbinding=invited-whale-ingress-azure
                    app=ingress-azure
                    pod-template-hash=5d65689dd
                    release=invited-whale
Annotations:        <none>
Status:             Running
IP:                 20.20.0.14
Controlled By:      ReplicaSet/invited-whale-ingress-azure-5d65689dd
Containers:
  ingress-azure:
    Container ID:   docker://0a233c3e696227123ba1820b58c525792e19e00506f8eadaeb28f2f4533eac26
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c110f441f81fc53060d4a88367ca9430c681e9a513cc978d55bed8c9025e9121
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 04 Jul 2019 12:30:12 +0530
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      invited-whale-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  akswithappgw-dns-e84e861d.hcp.centralindia.azmk8s.io
      KUBERNETES_PORT:               tcp://akswithappgw-dns-e84e861d.hcp.centralindia.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://akswithappgw-dns-e84e861d.hcp.centralindia.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       akswithappgw-dns-e84e861d.hcp.centralindia.azmk8s.io
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from invited-whale-sa-ingress-azure-token-r4vgn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  invited-whale-sa-ingress-azure-token-r4vgn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  invited-whale-sa-ingress-azure-token-r4vgn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```
* Output of `kubectl logs <ingress controller>. 
```
ERROR: logging before flag.Parse: I0705 04:45:01.499784       1 eventqueue.go:60] Enqueuing skip(false) item
ERROR: logging before flag.Parse: I0705 04:45:01.500065       1 eventqueue.go:119] Processing event begin, time since event generation: 283.602µs
ERROR: logging before flag.Parse: I0705 04:45:01.500165       1 controller.go:50] controller.processEvent called with type k8scontext.Event
ERROR: logging before flag.Parse: I0705 04:45:01.545295       1 controller.go:98] ~~~~~~~~ ↓ ApplicationGateway deployment ↓ ~~~~~~~~
ERROR: logging before flag.Parse: I0705 04:45:21.879573       1 controller.go:112] deployment took 20.334229047s
ERROR: logging before flag.Parse: I0705 04:45:21.879670       1 controller.go:119] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
ERROR: logging before flag.Parse: I0705 04:45:21.879714       1 eventqueue.go:128] Processing event done, updating lastEventTimestamp
ERROR: logging before flag.Parse: I0705 04:54:06.476173       1 eventqueue.go:60] Enqueuing skip(false) item
ERROR: logging before flag.Parse: I0705 04:54:06.476491       1 eventqueue.go:119] Processing event begin, time since event generation: 319.402µs
ERROR: logging before flag.Parse: I0705 04:54:06.476523       1 controller.go:50] controller.processEvent called with type k8scontext.Event
ERROR: logging before flag.Parse: I0705 04:54:06.606571       1 controller.go:98] ~~~~~~~~ ↓ ApplicationGateway deployment ↓ ~~~~~~~~
ERROR: logging before flag.Parse: I0705 04:54:27.046162       1 controller.go:112] deployment took 20.439555095s
ERROR: logging before flag.Parse: I0705 04:54:27.046263       1 controller.go:119] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
ERROR: logging before flag.Parse: I0705 04:54:27.046297       1 eventqueue.go:128] Processing event done, updating lastEventTimestamp
```

* Any Azure support tickets associated with this issue.
119070523000775

**Comment by draychev** [comment]
Hi @mtuppad,

From the format of the logs you attached to this issue I see that you are using a relatively old version of the Ingress Controller. 

Please follow [this document](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/cdeee91ee11f0c4bae0586932de0e51c54b22bdc/docs/how-tos/helm-upgrade.md#upgrading-agic-using-helm) to upgrade to the latest version of AGIC (as of this writing this is 0.7.1)

AGIC has a way to enable verbose logging, which would show you detailed information on what configuration it is applying to the Azure Application Gateway. [Here is how to](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/ec009ede61626e0153f14331df2a638cad6583a2/docs/troubleshooting.md#logging-levels) enable verbose logging, should that be necessary after you upgrade.

If you're still seeing `502 Bad Gateway` after the upgrade, could you please enable verbose logging and attach these here (with some sanitization of sensitive data).  I'd love to also see the Kubernetes Service YAML - do we actually have the services referenced in the Ingress - the latest version of AGIC would log an error when these are not setup correctly.

Would love to get your feedback on documentation, logging, upgrade process etc.

**Comment by mtuppad** [comment]
Thanks @draychev 
I followed you suggestion. 
- Upgraded AGIC to 0.7.1 
- Enabled verbose logging (I feel we need update the documentation here - as it is not there in sample file) 

Still got 502 error. 

When I looked at health probes - it was using host name as localhost ( as I didn't mentions host name in my ingress and path to /api/*
However my api app doesn't have any response for /api/*. So it was showing unhealthy. 

So I changed my ingress controller to 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: tupakscin.centralindia.cloudapp.azure.com
    http:
      paths:
      - path: /api/values
        backend:
          serviceName: apiservice
          servicePort: 80
      - backend:
          serviceName: frontend
          servicePort: 80
```

Now it works fine. 

Have question
what if my api host have multiple end points such as
/api/values
/api/getcustomer
/api/getvehicles

what would be my ingress controller config looks like?
Do I need to create 3 different path to point to same service?
is there any way to use /api/* and mention custom probe?

**Comment by mtuppad** [comment]
I was able to update my deployment yaml as below and use wild card path specification. Now I can access my apis. 
Updated yaml files. 
```
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  labels:
    app: apiapp
    tier: backend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apiapp
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: apiapp
spec:
  selector:
    matchLabels:
      app: apiapp
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: apiapp
        tier: backend
    spec:
      containers:
      - name: apiapp
        image: myacr.azurecr.io/apisample
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        readinessProbe:
          httpGet:
            path: /api/values
            port: 80
          periodSeconds: 30
          timeoutSeconds: 3
        env:
        - name: GET_HOSTS_FROM
          value: dns
          ports:
        - containerPort: 80
```

updated ingress controller. 
```

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: tupakscin.centralindia.cloudapp.azure.com
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: apiservice
          servicePort: 80
      - backend:
          serviceName: frontend
          servicePort: 80
```

Thanks again for the help.
