### ISSUE TITLE
Can this be used on baremetal k8s within azure using kubenet?

### ISSUE THREAD

**Issue by sharkymcdongles** [Azure/application-gateway-kubernetes-ingress#420]
we use baremetal for our k8s in azure, so it'd be nice if I could use this instead of nginx ingress to use as a waf.

**Comment by sharkymcdongles** [comment]
So I was able to deploy the helm chart and authenticate using the service principal. It seems to work and I see the azure portal shows that it is managed by k8s now. However it then loops to create the ingress rules on the WAF and I see it try then cancel with this:

> I0731 15:09:25.745403       1 process.go:116] Applied App Gateway config in 15m0.363522525s
> W0731 15:09:25.745441       1 process.go:121] Unable to deploy App Gateway config.Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
> I0731 15:09:25.745460       1 process.go:122] END ApplicationGateway deployment
> E0731 15:09:25.745467       1 eventqueue.go:113] Processing event failed:unable to deploy App Gateway config

**Comment by sharkymcdongles** [comment]
My ingress object:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: 4g
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: azure/application-gateway
    kubernetes.io/tls-acme: "true"
  creationTimestamp: "2019-07-31T15:02:21Z"
  generation: 1
  name: pentest.mip-ppr
  namespace: mip-ppr
spec:
  rules:
  - host: pentest.mip-ppr.censored.com
    http:
      paths:
      - backend:
          serviceName: local-login-ui-service
          servicePort: business
        path: /login
      - backend:
          serviceName: token-business-service
          servicePort: business
        path: /authorize
      - backend:
          serviceName: token-business-service
          servicePort: business
        path: /token
      - backend:
          serviceName: infrastructure-auth-ambassador
          servicePort: http
        path: /
  tls:
  - hosts:
    - pentest.mip-ppr.censored.com
    secretName: pentest.mip-ppr.censored.com
status:
  loadBalancer: {}
```
Where am I going wrong, or is the rule application just that long that it can timeout? I find any app gateways I make take over 20 minutes just to deploy with no rules.
