### ISSUE TITLE
Auto generated health probes does not match yaml livenessProbe port specification

### ISSUE THREAD

**Issue by ingenfakir** [Azure/application-gateway-kubernetes-ingress#472]
**Describe the bug**
We are exposing our health probes from our services on a different port than what our rest interfaces are exposed on.
We have defined the livenessProbe specifying one of the exposed ports to be used.
When I deploy my k8s template with the azure application gateway ingress it creates one health probe for each exposed port in the service even though I've explicitly set the port in the livenessProbe to one specific port.

This causes an issue as we receive a 502 when trying to use the rest endpoints, (as they are reported as not healthy by the application gateway).

The "real" health check endpoints work fine as there's actually something there on that container port that listens to /health/main.

**To Reproduce**
```
# deployment
[...]
ports: 
- containerPort: 9000
 name: rest
- containerPort: 9100
 name: health
livenessProbe:
 httpGet:
  path: /health/main
  port: health
[...]
# service

[...]
ports:
- port: 9000
 targetPort: rest
 name: rest
- port: 9100
  targetPort: health
 name: health
[...]
# ingress
[...]
paths:
- path: /users
 backend:
  serviceName: my-service
  servicePort: 9000
- path: /health/main
 backend:
  serviceName: my-service
  servicePort: 9100

```

![Screenshot from 2019-08-12 11-23-33](https://user-images.githubusercontent.com/9250118/62855951-d9489c00-bcf3-11e9-82ab-075dddd5175c.png)

As you can see, we get two probes even though I've specified that the livenessProbe should be on port 9100.
