### ISSUE TITLE
Path not removed & ssl redirect for default backend

### ISSUE THREAD

**Issue by cubed-it** [Azure/application-gateway-kubernetes-ingress#490]
I have set up aks etc according to the tutorial. I also have rbac active and shared to true. Version 0.8.0.

[1] I did the whole thing twice and on the second run I created the following problem: On the second run I directly specified a path, as it is called "Integrate with other services" - see below. 
Now the ssl redirect only works for the path but not for the default backend.

[2] If I remove the path again and specify only one backend, the path will not be removed. If I change the path, the change is applied.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway    
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  tls:
    - secretName: tlscer
  rules:
  - http:
      paths:
      - path: /hello/*
        backend:
          serviceName: frontendalt
          servicePort: 80
      - backend:
          serviceName: frontend
          servicePort: 80
```
