### ISSUE TITLE
Question / Sample Request -> nginx.ingress.kubernetes.io/configuration-snippet

### ISSUE THREAD

**Issue by ChrisRichner** [Azure/application-gateway-kubernetes-ingress#513]
In our nginx  based setup we used the following rewrite rules for our vue-js Single Page Applications (SPA).

```
nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/admin-dashboard)$ $1/ permanent;
      rewrite ^(/service-dashboard)$ $1/ permanent;
```

Could you please show me how to do the same thing in an azure ingress based setup?

Thanks

**Comment by delqn** [comment]
@ChrisRichner we don't yet support URL rewrites.

It looks like you want Nginx to append a trailing slash to the dashboard URLs?

What about a workaround - couldn't you add both of these URLs to the Kubernetes Ingress resource and then also tweak the backend HTTP handlers?

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: www.contoso.com
      http:
        paths:
          - path: /admin-dashboard
            backend:
              serviceName: svc
              servicePort: 80

          - path: /admin-dashboard/
            backend:
              serviceName: svc
              servicePort: 80
```
