### ISSUE TITLE
Redirect ingress pathbased route to external site

### ISSUE THREAD

**Issue by Baklap4** [Azure/application-gateway-kubernetes-ingress#534]
**Is your feature request related to a problem? Please describe.**
Is it possible to create a redirection rule to an external website?
For example you have an ingress controller with host: test.domain.com and a path based rule `/kibana` i'd love to redirect this to the cloud environment of elastic search, which has some weird url like `https://51584e5daa8d66s.eu-central-1.aws.cloud.es.io:9243`

**Describe the solution you'd like**
The nginx ingress uses an annotation like the following: `nginx.ingress.kubernetes.io/permanent-redirect: https://51584e5daa8d66s.eu-central-1.aws.cloud.es.io:9243` to make this happen.

I can setup such a rule within the portal itself but it does get overwritten bij AGIC  every once in a while.. so that's not doable

**Comment by delqn** [comment]
@Baklap4 even though App Gateway supports redirect to an external URL - we don't have an annotation for the ingress controller to do that.
That'd be a great feature to add.  I'm going to tag the issue, but not sure how long it'd take us to get to this. Would you be able to take a stab at adding the annotation to this repo?

**Comment by ALSHARIFcanbany** [comment]
[نسخة نسخة حولات وسترونن makkah  Riyadh@bank.comWestronAbdullah Saudi Arabia.pdf](https://github.com/Azure/application-gateway-kubernetes-ingress/files/3718912/makkah.Riyadh%40bank.comWestronAbdullah.Saudi.Arabia.pdf)

**Comment by ALSHARIFcanbany** [comment]
ALSHARIFcanbany is my new job manager and my ALSHEHRIF is my name isABDULLAH NASSER HAMID ALSHARIF is a new from Saudi Arabia in Makkah in Jamom

**Comment by aleksmark** [comment]
@bakla4 How exactly nginx permanent-redirect works if multiple hostnames/paths are configured? For example, if we have an ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: www.siteA.com
    http:
      paths:
      - path: /path1
        backend:
          serviceName: backend-a-1
          servicePort: 80
      - path: /path2
        backend:
          serviceName: backend-a-2
          servicePort: 80
  - host: www.siteB.com
    http:
      paths:
      - path: /pathb1
        backend:
          serviceName: backend-b-1
          servicePort: 80
      - path: /pathb2
        backend:
          serviceName: backend-b-2
          servicePort: 80
```

I don't see how can we set the redirection www.siteB.com/pathb1 to https://google.com with annotation described in https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect

> nginx.ingress.kubernetes.io/permanent-redirect: https://www.google.com

Unless the annotation will set the redirect to external site to all paths in the ingress file. Then we have  www.siteB.com/pathb1 path in a separate ingress.yaml file and achieve desired behavior?
