### ISSUE TITLE
The spec for ClusterIssues has changed - documentation requires an update

### ISSUE THREAD

**Issue by CameronAM** [Azure/application-gateway-kubernetes-ingress#602]
**Describe the bug**
As of cert-manager 0.8, the spec for ClusterIssuers has changed, the howto docs need to be updated to reflect that change.

Cert-manager have changed the [format of the ACME issuer spec](https://docs.cert-manager.io/en/latest/tasks/issuers/setup-acme/index.html), deprecating the `issuer.spec.acme.http01` and `issuer.spec.acme.dns01` resources, in favour of `issuer.spec.acme.solvers...` resources.

The example ClusterIssuer in the howto (https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/lets-encrypt.md) should have the be updated to use the new format, eg: 

```
#!/bin/bash
kubectl apply -f - <<EOF
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
name: letsencrypt-staging
spec:
acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: <YOUR.EMAIL@ADDRESS>
    # ACME server URL for Let’s Encrypt’s staging environment.
    # The staging environment will not issue trusted certificates but is
    # used to ensure that the verification process is working properly
    # before moving to production
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
    # Secret resource used to store the account's private key.
    name: example-issuer-account-key

    # Enable the HTTP-01 challenge provider
    # you prove ownership of a domain by ensuring that a particular
    # file is present at the domain
    solvers:
    - http01:
        ingress: 
            class: azure/application-gateway
EOF
```
