### ISSUE TITLE
Integration with DNS Zone

### ISSUE THREAD

**Issue by hkamel** [Azure/application-gateway-kubernetes-ingress#615]
**Is your feature request related to a problem? Please describe.**
Not a problem, it's an enhancement to be considered.

Ability to creates public/private accessible DNS names for application endpoints.

**Describe the solution you'd like**
Creation of DNS Zone in the Azure subscription and watches for Kubernetes Ingress resources and creates DNS A records in the cluster-specific DNS zone.

The concept is the same as implemented on [HTTP application routing
](https://docs.microsoft.com/en-us/azure/aks/http-application-routing)

**Comment by DenisBiondic** [comment]
You should be able to use https://github.com/kubernetes-sigs/external-dns for this

**Comment by akshaysngupta** [comment]
@hkamel Did you try the documentation on ExternalDNS with Azure DNS zones ? https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md

**Comment by Morriz** [comment]
It works with external-dns but not when using `annotation-filter`, so you will get issues in external-dns when you run multiple ingress controllers side by side. This might be a compound issue related to the following bugs:

https://github.com/Azure/application-gateway-kubernetes-ingress/issues/699
https://github.com/kubernetes-sigs/external-dns/issues/1336
https://github.com/kubernetes-sigs/external-dns/issues/1335

**Comment by jelster** [comment]
The AKS docs for the http-routing-addon state that you shouldn't use it for production scenarios, yet when it comes to using something like AGW in production you're forced to reverse-engineer the thing about http-routing-addon that makes it so clutch: the automatic DNS management. 

I know that in concept, adapting how the http-routing-addon integrates with ExternalDNS should be easy to copy by setting EDNS up from scratch along with AGWKI, but it (along with the above-mentioned #699 mentioned) make it feel like it's a huge step backwards in terms of the user experience.

**Comment by Mahesh-MSFT** [comment]
@akshaysngupta I have tried setting up AGIC using [ExternalDNS with Azure DNS zones](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/azure.md). It doesn't work!. Below is my manifest.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sba-ingress
  annotations:
    kubernetes.io/ingress.class: azure-application-gateway
spec:
  rules:
  - host: sba3.aks-egress-fw.io
    http:
      paths:
      - backend:
          serviceName: sba-service
          servicePort: 80
        path: /
```
ExternalDNS do update the A and TXT records in Azure DNS Zone with public IP of Application Gateway. But if I try to navigate to HOST (sba3.aks-egress-fw.io), I get an error `This site can’t be reached sba3.aks-egress-fw.io’s server IP address could not be found`.

ExternalDNS team [says](https://github.com/kubernetes-sigs/external-dns/issues/1675) it's an issue related to DNS.

I am not sure though if it's Application Gateway or DNS issue.

Any thoughts?
