### ISSUE TITLE
Setting request-timeout results in 502 - Bad Gateway

### ISSUE THREAD

**Issue by onybo** [Azure/application-gateway-kubernetes-ingress#653]
Setting the request timeout by adding an annotation to my ingress.yaml will make the gatway report 502 - Bad Gateway.

**To reproduce:**
apply a yaml file such as this:
```
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/request-timeout: 40
spec:
  tls:
    - hosts:
        - somename.mydomain
      secretName: my-tls-secret-name
  rules:
    - host: somename.mydomain
      http:
        paths:
          - path: /myservice/*
            backend:
              serviceName: myservice
              servicePort: 80
```

**Application gateway ingress controller Version:**
mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.7.1
