### ISSUE TITLE
Issue using both public and private listener with different ports

### ISSUE THREAD

**Issue by InsOpDe** [Azure/application-gateway-kubernetes-ingress#672]
**Describe the bug**
I have Ingresses on Port 80 and 443 which are public. Now I am trying to create an Ingress for private-Ips. I know that I cannot reuse 80 and 443 for that, so I am trying to use different ports but with no success.

I am getting following Error:
> E1126 13:22:55.640499       1 frontend_listeners.go:47] Can't assign port fp-80 to Private IP Listener fl-kiali.cloud.example.com-80-privateip; already assigned to Public IP Listener fl-admin-portal.cloud.example.com-80; Will not create listener {FrontendPort:80 HostName:kiali.cloud.example.com UsePrivateIP:true}

**To Reproduce**
Just apply both ingress-resources with their appurtenant services and deployments

**Ingress Controller details**
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/use-private-ip: "true"
    kubernetes.io/ingress.class: azure/application-gateway
  name: kiali
  namespace: istio-system
spec:
  rules:
  - host: kiali.cloud.example.com
    http:
      paths:
      - backend:
          serviceName: kiali
          servicePort: 20001
status:
  loadBalancer: {}
```
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: azure/application-gateway
  name: admin-portal
  namespace: istio-system
spec:
  rules:
  - host: admin-portal.cloud.example.com
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80
  tls:
  - hosts:
    - admin-portal.cloud.example.com
    secretName: admin-portal-staging
status:
  loadBalancer: {}
```
