### ISSUE TITLE
Question: How to support multiple AGIC with multiple AGW in a single AKS cluster using IngressClass

### ISSUE THREAD

**Issue by jsco2t** [Azure/application-gateway-kubernetes-ingress#732]
Hi,

I have been digging through the documentation and I apologize if I have missed this. Here is the scenario I am trying to solve for:

- A single AKS Cluster
- Two App Gateways (configured with different routing/firewall rules)
- Two App Gateway Ingress Controllers

Basically (and this is over simplified). Say I have two kinds of workloads. Web Services and API Services. I want both workloads to run from the same cluster, but I need the Web "traffic" to be routed through one of the two App Gateways and the API "traffic" to be routed through the other App Gateway. In this scenario each App Gateway will have custom configuration in regards to it'security/firewall. 

As far as I can see - when you setup an AGIC (via Helm) you tell it which **single** AGW it should manage. Based on this - I was thinking that for my scenario I would need paired instances of AGIC's and AGW's

Web Services:
  AGW 1 <---> AGIC 1

API Services:
  AGW 2 <---> AGIC 2

I don't see any clear info in the documents about how to do this. Typically I would expect to see some sort of support (at least) for setting the `Ingress Class Name` for each Ingress Controller so that `Ingress Resources` could point to the correct controller (and by extension AGW):

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-something
  labels:
    app: some-cool-api-trust-me
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway <-----------------!!!
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
...
```

Any assistance you can provide would be greatly appreciated!

Thanks!
