### ISSUE TITLE
AGIC Not Running in Azure VA Gov Cloud 

### ISSUE THREAD

**Issue by flyer299** [Azure/application-gateway-kubernetes-ingress#735]
**Describe the bug**
The AGIC does not seem to want to run and function.   The big difference for us is that we are running in the Azure Gov Cloud and not the Commercial Cloud.    I've already noticed a few features not supported in order to get through the tutorial.   

Also another Warning, I am a complete newbie to AKS and K8S.  I have had some experience in the past in the Google Compute Cloud, but I am basically starting from zero and know way less than I need to.  

**To Reproduce**
I've been following the Greenfield deployment tutorial:  https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new/

1st Issue came when I tried to run the step to create the deployment for AGIC.
`az group deployment create -g $resourceGroupName -n $deploymentName --template-file template.json --parameters parameters.json`

I would get an error message:

```
Azure Error: InvalidTemplateDeployment
Message: The template deployment 'nxt-dev-ingress' is not valid according to the validation procedure. The tracking id is '6d22cfe1-3a41-4f62-a5ea-fbefa7a96dc9'. See inner errors for details.
Exception Details:
Error Code: OperationNotAllowed
Message: Provisioning of resource(s) for container service aks3fd6 in resource group NXT-DEV-VA failed. Message: {
'code': 'OperationNotAllowed',
'message': 'Addon 'httpApplicationRouting' is not supported in this cloud environment.'
}. Details:
```

I've been following this other issue:
https://github.com/Azure/application-gateway-kubernetes-ingress/issues/668

I've tried commenting out the Liveness and Readyness Probe, which gets the pod running.   

But when I try and continue the tutorial at: 
https://azure.github.io/application-gateway-kubernetes-ingress/tutorial/

The Ingress Controller is running, but it doesn't seem to do anything.  I would expect that I can see some Backend Targets in the Application Gateway UI in Azure, and that there would be a public IP address somewhere for the FrontEnd Service in the Tutorial.  But there isn't. 

**Ingress Controller details**
```
PS C:\Users\ken.veard\source\AKS> kubectl describe pod ingress-azure-1581627607-5865bc5649-pt8wj
Name:           ingress-azure-1581627607-5865bc5649-pt8wj
Namespace:      default
Priority:       0
Node:           aks-agentpool-35064155-2/10.0.0.66
Start Time:     Fri, 14 Feb 2020 09:53:05 -0600
Labels:         aadpodidbinding=ingress-azure-1581627607
                app=ingress-azure
                pod-template-hash=5865bc5649
                release=ingress-azure-1581627607
Annotations:    prometheus.io/port: 8123
                prometheus.io/scrape: true
Status:         Running
IP:             10.0.0.75
Controlled By:  ReplicaSet/ingress-azure-1581627607-5865bc5649
Containers:
  ingress-azure:
    Container ID:   docker://69f7dbaa058665b974e9258af5283e6c73339e3c4d4c8832fbfe01266a828591
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c295f99ae66443c5a392fd894620fcd1fc313b9efdec96d13f166fefb29780a9
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Fri, 14 Feb 2020 10:23:58 -0600
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Fri, 14 Feb 2020 10:13:44 -0600
      Finished:     Fri, 14 Feb 2020 10:23:56 -0600
    Ready:          True
    Restart Count:  3
    Environment Variables from:
      ingress-azure-1581627607  ConfigMap  Optional: false
    Environment:
      AZURE_CONTEXT_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:           ingress-azure-1581627607-5865bc5649-pt8wj (v1:metadata.name)
      AGIC_POD_NAMESPACE:      default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-1581627607-token-shmwn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-1581627607-token-shmwn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-1581627607-token-shmwn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age                  From                               Message
  ----    ------     ----                 ----                               -------
  Normal  Scheduled  39m                  default-scheduler                  Successfully assigned default/ingress-azure-1581627607-5865bc5649-pt8wj to aks-agentpool-35064155-2
  Normal  Pulling    8m25s (x4 over 39m)  kubelet, aks-agentpool-35064155-2  Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.0"
  Normal  Pulled     8m25s (x4 over 39m)  kubelet, aks-agentpool-35064155-2  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.0.0"
  Normal  Created    8m25s (x4 over 39m)  kubelet, aks-agentpool-35064155-2  Created container ingress-azure
  Normal  Started    8m24s (x4 over 39m)  kubelet, aks-agentpool-35064155-2  Started container ingress-azure
```

```PS C:\Users\ken.veard\source\AKS> kubectl logs ingress-azure-1581627607-5865bc5649-pt8wj
ERROR: logging before flag.Parse: I0214 19:28:07.385875       1 main.go:302] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0214 19:28:07.587738       1 environment.go:168] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0214 19:28:07.587764       1 main.go:132] App Gateway Details: Subscription: fad8470a-e1a9-4209-b526-011761c080a0, Resource Group: NXT-DEV-VA, Name: applicationgateway3fd6
I0214 19:28:07.587774       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
```
```PS C:\Users\ken.veard\source\AKS> helm list
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-azure-1581627607        default         1               2020-02-13 21:00:09.617162874 +0000 UTC deployed        ingress-azure-1.0.0     1.0.0```

Azure Ticket:120021224004039

**Comment by akshaysngupta** [comment]
@flyer299 Thanks for reporting. Here is how you work around the two issues:
1. For template validation error, after downloading the arm template, you should remove the `httpApplicationRouting` and then try again.
2. Second issue is related to AGIC not using the right endpoints for ARM/AAD in VA Gov cloud. These endpoints vary based on the cloud environment.'
This can be configured easily by setting `environment` in the [helm config](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/ff348df82ab067285478ea82bf80bcef493f7e26/helm/ingress-azure/values.yaml#L34).
Try setting this to `AZUREUSGOVERNMENTCLOUD`.

**Comment by bg2s0r** [comment]
> @flyer299 Thanks for reporting. Here is how you work around the two issues:
> 
> 1. For template validation error, after downloading the arm template, you should remove the `httpApplicationRouting` and then try again.
> 2. Second issue is related to AGIC not using the right endpoints for ARM/AAD in VA Gov cloud. These endpoints vary based on the cloud environment.'
>    This can be configured easily by setting `environment` in the [helm config](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/ff348df82ab067285478ea82bf80bcef493f7e26/helm/ingress-azure/values.yaml#L34).
>    Try setting this to `AZUREUSGOVERNMENTCLOUD`.

Sir, I think the `environment` variable is not implemented, I set the environment variable, but it still request the wrong endpoint. #740

**Comment by flyer299** [comment]
I had an open case with Azure Support and got the word back from the product team that the AGIC won't work in the Gov Cloud for a reason that wasn't specified.  They said that there is no timeline to resolve what ever issue they found.  

I will try these suggestions to see if perhaps they are wrong and it might work, but I am not very hopeful at this time.

**Comment by flyer299** [comment]
The files I have to work with don't exactly line up with the instructions that you gave me to follow, but I tried to follow them the best I could and research to make sure I did it right.   You pointed me to a helm config file called values.yaml.  Yet following the tutorial that I referenced in my original post, we end up with a file called helm-config.yaml, and that file does not have any of the comments in there referring to the environment variable you referenced.  

So we added it, and installed the Helm Chart.   It still doesn't work. 

The Helm-Config.yaml we have now looks like (I've redacted Subscription IDs and other IDs with ***):
```

# This file contains the essential configs for the ingress controller helm chart

# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 5

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: ****
    resourceGroup: NXT-DEV-VA
    name: applicationgateway3fd6
    usePrivateIP: false
    environment: AZUREUSGOVERNMENTCLOUD

    # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
    # This prohibits AGIC from applying config for any host/path.
    # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
    shared: false

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
# Leaving this variable out or setting it to blank or empty string would
# result in Ingress Controller observing all acessible namespaces.
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
armAuth:
    type: aadPodIdentity
    identityResourceID: ***
    identityClientID:  ***

## Alternatively you can use Service Principal credentials
# armAuth:
#    type: servicePrincipal
#    secretJSON: <<Generate this value with: "az ad sp create-for-rbac --subscription <subscription-uuid> --sdk-auth | base64 -w0" >>

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
    enabled: false # true/false

# Specify aks cluster related information. THIS IS BEING DEPRECATED.
aksClusterConfiguration:
    apiServerAddress: <aks-api-server-address>

```
