### ISSUE TITLE
Enhance annotation list of AGIC

### ISSUE THREAD

**Issue by ipetrov117** [Azure/application-gateway-kubernetes-ingress#772]
## Is your feature request related to a problem? Please describe
Greetings! I am not sure whether this is a feature request, but I decided to post this here.

I think that it would be beneficial to support the override of the *Affinity cookie name* property in Application Gateway, as there are some applications which would not use the default affinity cookie name and would require a custom one.

In addition to this, it would be a good idea to also support the overwrite of the incoming HTTP host header, as the domain of some backends can be different from the DNS of the Application Gateway and the backend would rely on a specific host header to resolve to the correct endpoint.

Both these properties are valid for the application that I am trying to use AGIC with and would be very grateful if you consider if what is required is possible.

## Describe the solution you'd like
As a solution, I imagine having both properties added to the AGIC annotation list.

### Affinity cookie name
For this property it should only be working if ```appgw.ingress.kubernetes.io/cookie-based-affinity: "true"```

#### Usage
```yaml 
appgw.ingress.kubernetes.io/affinity-cookie-name: "value"
```
#### Example
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-server-ingress-affinity
  namespace: test-ag
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/affinity-cookie-name: "test"
spec:
  rules:
  - http:
      paths:
      - path: /hello/
        backend:
          serviceName: go-server-service
          servicePort: 80
```
#### Usage
To overwrite the HTTP host header with host from backend target:
```yaml 
appgw.ingress.kubernetes.io/overwrite-http-header-from-backend-target: "true"
```
To overwrite with specific domain:
```yaml 
appgw.ingress.kubernetes.io/overwrite-http-header: "example.com"
```
#### Example 1
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-server-ingress-affinity
  namespace: test-ag
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/overwrite-http-header-from-backend-target: "true"
spec:
  rules:
  - http:
      paths:
      - path: /hello/
        backend:
          serviceName: go-server-service
          servicePort: 80
```
#### Example 2
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-server-ingress-affinity
  namespace: test-ag
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/overwrite-http-header: "example.com"
spec:
  rules:
  - http:
      paths:
      - path: /hello/
        backend:
          serviceName: go-server-service
          servicePort: 80
```
## Conclusion
Please let me know if I this functionality is already present and I have missed it for some reason.
If not please consider whether this is possible and how much time would it cost.
Thanks!

**Comment by bgvladedivac** [comment]
guys, any idea at what stage is this feature ?

**Comment by 3quanfeng** [comment]
Hi @ipetrov117, Thanks for sharing your idea, it's great!
If I understood correctly regarding "appgw.ingress.kubernetes.io/overwrite-http-header: "example.com"", you would like to override the host name appgw sends to the backend, in this case, you may try one of the existing annotation which is[ backend-hostname](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#backend-hostname).
For the ability to override the host name in the response header, good news is we already have it in our backlog, we will send out an update once we have that ready.
Regarding the customized cookie affinity naming, may I ask Why the naming is important to your case?
Thanks again for sharing your great thoughts!

**Comment by ma185360** [comment]
Team,

Please share a time line for this feature.

**Comment by rbickel** [comment]
Hi @3quanfeng, here is a scenario that is breaking for me:

I have 2 deployments, 1 listening in /webapp and the other on /identity. Each deployment has 2 replicas and session affinity enabled. 

When hitting /webapp, the ApplicationGatewayAffinity is set to the hash of the backend pod IP. Then the user is redirected to /identity to authenticate, the ApplicationGatewayAffinity is reset to the identity pod IP hash. Then the login is successful, user is redirected to /webapp, but the cookie doesn't match any backend pod ip hash (as reset by /identity path).

Application Gateway should solve this by having different affinity cookie per backend path, but in the meantime, the possibility to explicitly set different affinity cookie name would let us solve this case.

Happy to implement it quickly if needed :)

BR
Raphael

**Comment by rbickel** [comment]
Actually, we should have an annotation : `cookie-based-affinity-distinct-name: "true"`
When true, http settings of these backends will have a distinct affinity cookie name.
This would enable to have such ingress manifest:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kony-fabric-ingress-public
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/cookie-based-affinity-distinct-name: "true"
spec:
  rules:
  - http:
      paths:
      - path: /webapp*
        backend:
          serviceName: webapp
          servicePort: 80
      - path: /identity*
        backend:
          serviceName: identity
          servicePort: 80
````
So far multiple path with different backend isn't support for cookie affinity
