### ISSUE TITLE
AGIC with Linkerd service mesh

### ISSUE THREAD

**Issue by thangchung** [Azure/application-gateway-kubernetes-ingress#805]
Currently, I'm working on the project that uses `nginx-ingress` in the `AKS cluster` - in-cluster ingress, and I read through some of the articles and news that with the `Azure Cloud platform` we can use `AGIC` to improve the performance of the application - [Application Gateway vs In-cluster Ingress](https://azure.microsoft.com/en-us/blog/application-gateway-ingress-controller-for-azure-kubernetes-service/). 

When I worked with `nginx-ingress`, and if we want to make it works correctly with Linkerd, then I need to inject `Linkerd` sidecar into it. I need to [configure some of YAML](https://linkerd.io/2/tasks/using-ingress/#nginx) on the ingress as below

```yaml
annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
```

But when I searched around in this repo, I didn't find anywhere describes about how can I make `AGIC` works well with `Linkerd` (with or without configuration to make it works well). 

My question is `Is it AGIC working well with Linkerd without needing to configure anything on the ingress or I need to do something?` 

Please help to point out where can I find the guidance to inject `Linkerd` to `AGIC`. Thank you very much.
