### ISSUE TITLE
AGIC not update backends when deployment replica chnage

### ISSUE THREAD

**Issue by nfinkel** [Azure/application-gateway-kubernetes-ingress#824]
Hi All,

My AGIC is not detect any change on endpoint list of my service and ingress.

i'm using AGIC helm install version 1.0.0 with aad-pod-identity version 1.5.5
when i update the replica count of my deployment i don't see any change on the AGIC log or configuration.
if i delete and recreate my ingress, the new/deleted PODs are added to the endpoint list.

**Deployemnt**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Service**
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
```

**Ingress**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  backend:
    serviceName: nginx
    servicePort: http
```

after deploy all 3 components, i can see the correct configuration on the AG with single endpoint.
then i increase the deployment replica count and there is no change on AG and no logs on AGIC,
i can see the new PODs added to the service and ingress as endpoints.
`kubectl scale deployment nginx-deployment --replicas=3`
but if i delete and apply the ingress, all 3 pods are added to the AG.

Appreciate your help
Nir

**Comment by 3quanfeng** [comment]
Hi @nfinkel , Thanks for reporting the issue, we are evaluating the issue, instead, could you please use the alternative in your ingress configure?
`spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80`

**Comment by nfinkel** [comment]
Hi @3quanfeng 

The workaround work without any problem.
please find the updated ingress configuration.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: http
```
