### ISSUE TITLE
Multiple Ingress with Path based rule is not working without specifying backend-path-prefix

### ISSUE THREAD

**Issue by prabdeb** [Azure/application-gateway-kubernetes-ingress#848]
**Describe the bug**
Multiple Ingress with Path based rule is not working while using IP address, however after specifying `backend-path-prefix` in annotation they started working.

Not sure if this is a bug or this is how it should work. If this is how it should work then it should be documented.

The current document of [bacend-path-prefix](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#backend-path-prefix) does not talk about this scenario.

**To Reproduce**

This following ingress resources **do not** work -
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-a
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /backend-a
        backend:
          serviceName: backend-a
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-b
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /backend-b
        backend:
          serviceName: backend-b
          servicePort: 80
```

However after adding `backend-path-prefix` annotation, following ingress resources work -
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-a
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /backend-a
        backend:
          serviceName: backend-a
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-b
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /backend-b
        backend:
          serviceName: backend-b
          servicePort: 80
```

**Note:** `backend-a` and `backend-b` both are having `/` as service start point in the backend K8's `services`
