### ISSUE TITLE
Auth Proxy Support

### ISSUE THREAD

**Issue by erikschlegel** [Azure/application-gateway-kubernetes-ingress#860]
**Is your feature request related to a problem? Please describe.**
The customer I'm working with requires JWT auth token validation for all ingress activity. We're unclear with available aproaches for setting up an authentication proxy for our frontend AGIC route. Our identity provider is AAD. 

Nginx supports this today via 
```
annotations:
  kubernetes.io/ingress.class: nginx
  nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.default.svc.cluster.local:4180/oauth2/auth"
  nginx.ingress.kubernetes.io/auth-signin: "http://<DNS prefix>.<azure region>.cloudapp.azure.com/oauth2/start"
```
Are there any alternative approaches that would support this use-case today?

**Describe the solution you'd like**
A new annotation in the AGIC where we can provide the authentication url and signin endpoint for the ingress controller.
