### ISSUE TITLE
Add support for configuring backend HTTP settings

### ISSUE THREAD

**Issue by Jawshua** [Azure/application-gateway-kubernetes-ingress#88]
**Is your feature request related to a problem? Please describe.**
There are a few settings that we currently have to manually configure after the backend settings have been created by the ingress. Primarily we need to enable connection draining and increase the request timeout, but I imagine the ability to configure the rest of the settings would come in handy for others.

**Describe the solution you'd like**
The nginx Ingress handles this with annotations, for example:
```yaml
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy‑connect‑timeout: 30
```

I imagine this could be handled in a similar fashion:
```yaml
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: example
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/http-cookie-based-affinity: "false"
    appgw.ingress.kubernetes.io/http-connection-draining: "true"
    appgw.ingress.kubernetes.io/http-request-timeout: "30"
```
