### ISSUE TITLE
Secret not found by controller

### ISSUE THREAD

**Issue by drunetovich** [Azure/application-gateway-kubernetes-ingress#903]
Hello, after deployment controller only creates http rules, complains on missing secret, however secret surely exists:

events:
NAMESPACE     LAST SEEN   TYPE      REASON           OBJECT                           MESSAGE
recommender   14s         Warning   SecretNotFound   ingress/recommender-mltemplate   Unable to find the secret associated to secretId: [recommender/rringresstls]

secrets:
NAMESPACE         NAME                                             TYPE                                  DATA   AGE
recommender       rringresstls                                     Opaque                                2      81m

IngressConfig:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $serviceName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class:  azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Release.Namespace }}.rr.local
    secretName: "rringresstls"
  rules:
  - host: "{{ .Release.Namespace }}.rr.local"
    http:
      paths:
        - backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }} 
{{- end }}

```
