### ISSUE TITLE
Separate Host header from CN for end to end TLS

### ISSUE THREAD

**Issue by DiegoBallve** [Azure/application-gateway-kubernetes-ingress#908]
**Is your feature request related to a problem? Please describe.**

I'm trying to ingress-azure to hit an IBM HTTP Server running inside kube. That server is just the entrypoint for a bigger solution (HCL Commerce) with more moving parts. I want to use SSL backends, so I need to enable end-to-end TLS. I do get it to connect to backend with version 1.2-rc3 and an ingress definition like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "livets-web.qa.svc.cluster.local"    
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "selfserve_production_pki_root_ca"
    kubernetes.io/ingress.class: azure/application-gateway
  name: live-azure-appg
spec:
  rules:
  - host: qa.sample.com
    http:
      paths:
      - backend:
          serviceName: livets-web
          servicePort: 443
        path: /
  tls:
  - hosts:
    - qa.sample.com
    secretName: sample-com-tls-certificate
```

The problem is that the web server relies on "Host" request header to perform redirects. The servers behind the webserver also use the "Host" request header (indirectly, using the $WSSN  header added by IBM HTTP Server PlugIn, which is initialized with the value from Host header).

Unfortunately Azure Application Gateway wants to use the same Host header to validate the certificate of my backend. And since the certificate is issued to internal hostname, "livets-web.qa.svc.cluster.local", that is the value passed by AppG in the Host request header.

Here is a custom log from the apache like web server when the request comes from Application Gateway. Note how Hosts has the cluster internal address "livets-web.qa.svc.cluster.local", not the public hostname "qa.sample.com":
```
{"type":"ihs-access",
"datetime":"2020-06-10T12:31:29.999 GMT",
"@version":"1",
"protocol":"HTTP/1.1",
"remoteHost":"10.13.2.5",
"port":443,
"method":"GET",
"url":"/wcs/resources/health/ping",
"query":"",
"status":200,
"bytes":0,
"elapsedTime":65278,
"referer":"-",
"x-forwarded-for":"193.65.1.2:30350",
"x-forwarded-host":"-",
"x-forwarded-port":"443",
"x-original-host":"qa.sample.com",
"x-forwarded-proto":"https",
"Host":"livets-web.qa.svc.cluster.local",
}
```

I have been successfully using ingress-nginx to go into the cluster. With that the Host header is the original hostname, and everything works as it should. The public hostname in this case is "web-live-qa.restricted.sample.com"

```
{"type":"ihs-access",
"datetime":"2020-06-10T12:31:24.999 GMT",
"@version":"1",
"protocol":"HTTP/1.1",
"remoteHost":"10.13.1.17",
"port":443,
"method":"GET",
"url":"/wcs/resources/healthping",
"query":"",
"status":200,
"bytes":0,
"elapsedTime":65215,
"referer":"-",
"x-forwarded-for":"10.13.1.66",
"x-forwarded-host":"web-live-qa.restricted.sample.com",
"x-forwarded-port":"443",
"x-original-host":"-",
"x-forwarded-proto":"https",
"Host":"web-live-qa.restricted.sample.com"
}
```

**Describe the solution you'd like**

I would like Azure  Application Gateway / ingress to support TLS and HTTPS backends without messing up with the hosts header, wich is used both by ingress and by backend services to do routings and redirects. Do collect the backend hostname in an annotation, but do not use it for Hosts header.
