### ISSUE TITLE
hostname-extension

### ISSUE THREAD

**Issue by aglees** [Azure/application-gateway-kubernetes-ingress#912]
We've come across a scenario whereby the hostname-extension annotation is used on two ingress resources. The ingress resources share the same hostname in the hostname-extension but different paths. However the AGIC logs throw an error indicating that:

```
E0611 21:01:06.671423       1 controller.go:141] network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayHttpListenersUsingSameFrontendPortHostNameAndFrontendIpConfig" Message="Two Http Listeners of Application Gateway fl-a50c63277cd6cd2b5b18b2494e6bdb66 and fl-73ff1c2e8ac88e73779e0ce4ab68976e are using the same Frontend Port /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Network/applicationGateways/{{applicationGateway}}/frontendPorts/fp-443, HostName {{commonHostname}} and FrontendIpConfiguration /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Network/applicationGateways/{{applicationGateway}}/frontendIPConfigurations/{{clusterName}}-feip." Details=[]
E0611 21:01:06.671435       1 worker.go:62] Error processing event.network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayHttpListenersUsingSameFrontendPortHostNameAndFrontendIpConfig" Message="Two Http Listeners of Application Gateway fl-a50c63277cd6cd2b5b18b2494e6bdb66 and fl-73ff1c2e8ac88e73779e0ce4ab68976e are using the same Frontend Port /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Network/applicationGateways/{{applicationGateway}}/frontendPorts/fp-443, HostName www.tesco.com and FrontendIpConfiguration /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Network/applicationGateways/{{applicationGateway}}/frontendIPConfigurations/{{clusterName}}-feip." Details=[]
```

To reproduce, here are the two ingress resources:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{tls-certName}}
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "60"
    appgw.ingress.kubernetes.io/hostname-extension: {{uniqueHostnameOne}},{{sharedHostname}}
    kubernetes.io/ingress.class: azure/application-gateway
  name: {{ingressOne}}
  namespace: {{nameSpaceOne}}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{serviceOne}}
          servicePort: 443
        path: /foo*
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{tls-certName}}
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "60"
    appgw.ingress.kubernetes.io/hostname-extension: {{uniqueHostnameTwo}},{{sharedHostname}}
    kubernetes.io/ingress.class: azure/application-gateway
  name: {{ingressTwo}}
  namespace: {{nameSpaceTwo}}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{serviceTwo}}
          servicePort: 443
        path: /bar*
```

It looks like the following method of defining hostnames & paths ingress works, along with removing the `hostname-extension` annotation:

```
spec:
  rules:
  - host: {{uniqueHostnameOne}}
    http:
      paths:
      - backend:
          serviceName: {{serviceOne}}
          servicePort: 443
        path: /foo*
  - host: {{sharedHostname}}
    http:
      paths:
      - backend:
          serviceName: {{serviceOne}}
          servicePort: 443
        path: /foo*
```
and for the other ingress

```
spec:
  rules:
  - host: {{uniqueHostnameTwo}}
    http:
      paths:
      - backend:
          serviceName: {{serviceTwo}}
          servicePort: 443
        path: /bar*
  - host: {{sharedHostname}}
    http:
      paths:
      - backend:
          serviceName: {{serviceTwo}}
          servicePort: 443
        path: /bar*
```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . 

```
Name:         {{clusterName}}-ingress-azure-8654b7f8f7-j7z4w
Namespace:    ingress-controller
Priority:     0
Node:         aks-{{smallClusterName}}-18787795-vmss00000z/10.117.69.66
Start Time:   Thu, 11 Jun 2020 22:00:25 +0100
Labels:       aadpodidbinding={{clusterName}}-ingress-azure
              app=ingress-azure
              pod-template-hash=8654b7f8f7
              release={{clusterName}}-ingress-azure
Annotations:  checksum/config: 2e70962c9aed2fb91a7c52e4ec178bbc515babe53581a19103916a062d29143b
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.117.69.76
IPs:
  IP:           10.117.69.76
Controlled By:  ReplicaSet/{{clusterName}}-ingress-azure-8654b7f8f7
Containers:
  ingress-azure:
    Container ID:   docker://3ef640d88bd1ffa56f464bbb171c44e6e7f1f722f1b848a574418d633b91d101
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:9331411a7f29cfd49b6d93e045ea6dea44cab07a2b4ce7d6a6448b3eb23d5200
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 11 Jun 2020 22:00:34 +0100
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      {{clusterName}}-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  {{clusterName}}-ingress-azure-8654b7f8f7-j7z4w (v1:metadata.name)
      AGIC_POD_NAMESPACE:             ingress-controller (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from {{clusterName}}-ingress-azure-token-m2tgg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  {{clusterName}}-ingress-azure-token-m2tgg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  {{clusterName}}-ingress-azure-token-m2tgg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                     Age                From                                                                    Message
  ----     ------                     ----               ----                                                                    -------
  Normal   Scheduled                  <unknown>          default-scheduler                                                       Successfully assigned ingress-controller/{{clusterName}}-ingress-azure-8654b7f8f7-j7z4w to aks-{{smallClusterName}}-18787795-vmss00000z
  Normal   Pulling                    13m                kubelet, aks-{{smallClusterName}}-18787795-vmss00000z                                 Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3"
  Normal   Pulled                     13m                kubelet, aks-{{smallClusterName}}-18787795-vmss00000z                                 Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0-rc3"
  Normal   Created                    13m                kubelet, aks-{{smallClusterName}}-18787795-vmss00000z                                 Created container ingress-azure
  Normal   Started                    13m                kubelet, aks-{{smallClusterName}}-18787795-vmss00000z                                 Started container ingress-azure
  Warning  Unhealthy                  12m (x3 over 13m)  kubelet, aks-{{smallClusterName}}-18787795-vmss00000z                                 Readiness probe failed: Get http://10.117.69.76:8123/health/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  FailedApplyingAppGwConfig  12m                azure/application-gateway, {{clusterName}}-ingress-azure-8654b7f8f7-j7z4w  network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayHttpListenersUsingSameFrontendPortHostNameAndFrontendIpConfig" Message="Two Http Listeners of Application Gateway fl-a50c63277cd6cd2b5b18b2494e6bdb66 and fl-73ff1c2e8ac88e73779e0ce4ab68976e are using the same Frontend Port /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}/providers/Microsoft.Network/applicationGateways/{{appGwName}}/frontendPorts/fp-443, HostName {{sharedHostname}} and FrontendIpConfiguration /subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroup}}//providers/Microsoft.Network/applicationGateways/{{appGwName}}/frontendIPConfigurations/smapps-feip." Details=[]
```

The <ingress controller> pod name can be obtained by running `helm list`. 

```
NAME                      	NAMESPACE         	REVISION	UPDATED                                	STATUS  	CHART                                                             	APP VERSION
{{clusterName}}-ingress-azure	ingress-controller	2       	2020-06-11 21:00:25.169750474 +0000 UTC	deployed	ingress-azure-1.2.0-rc3
```
