### ISSUE TITLE
SSL Redirection cannot be configured properly

### ISSUE THREAD

**Issue by rlevchenko** [Azure/application-gateway-kubernetes-ingress#914]
**Describe the bug**
My helm-managed ingress objects with url path-based routing, ssl offload and multiple hostnames features work fine, however, when I try to update them with ssl-redirect annotation the Ingress controller cannot properly apply a new configuration to application gateway. 

In that case, the controller only creates a HTTP listener and  a new rule (sslr-fl-09720eb9082cb7d02efdc60a169f3d35), see logs below) with a wrong type (Backend pool instead of the Redirection). As a result, such "configuration" opens a website on both 80 and 443 ports with no ssl-redirect configured. Have I missed any required configuration steps? Is it a bug?

**Steps to reproduce the behavior:**
Apply the ingress yaml files (below)

**Ingress Controller details**

Ingress version: 

1.2.0-rc1 , Kubernetes 1.16.9

Controller logs:

E0611 15:32:00.066922       1 requestroutingrules.go:258] Will not attach default redirect to rule; SSL Redirect does not exist: /subscriptions/xxxx/resourceGroups/cluster-k8s/providers/Microsoft.Network/applicationGateways/appgwf4f7/redirectConfigurations/sslr-fl-09720eb9082cb7d02efdc60a169f3d35

Ingress yaml (backend):

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-api-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: appgw-ingress-tls
  rules:
    - host: www.contoso.com
      http:
        paths:
          - path: /path1/*
            backend:
              serviceName: gateway-api
              servicePort: 80
          - path: /path2*
            backend:
              serviceName: gateway-api
              servicePort: 80
```
Ingress yaml (frontend, providing only different parts):

```
http:
        paths:
          - backend:
              serviceName: myservice
              servicePort: 80
```
