### ISSUE TITLE
Prometheus pushgateway behind AGIC not working

### ISSUE THREAD

**Issue by sudhakar890** [Azure/application-gateway-kubernetes-ingress#915]
**Describe the bug**
I've configured Prometheus pushgateway behind AGIC using below config

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pushgateway
  labels:
    app: pushgateway
    version: "1.2.0"
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: "example.com"
      http:
        paths:
          - path: /pushgateway
            backend:
              serviceName: pushgateway
              servicePort: 9091
```

Below is pushgateway deployment file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app: pushgateway
    version: "1.2.0"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pushgateway
      version: "1.2.0"
  template:
    metadata:
      labels:
        app: pushgateway
        version: "1.2.0"
    spec:
      serviceAccountName: pushgateway
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          args:
            - --web.external-url=http://example.com/pushgateway
            - --web.route-prefix=/
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: ///-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: ///-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
```
The pushgateway is not loading properly.

![image](https://user-images.githubusercontent.com/25337865/84703170-12771b80-af58-11ea-95a1-c40b730594fe.png)
**Ingress Controller details**
Ingress version: 1.2.0-rc3 
Kubernetes 1.16.8

I followed the Nginx config provided on Prometheus site. Am I missing any AGIC configurations?
