### ISSUE TITLE
This Basic HTTP listener cannot use the same frontend port as an existing listener.

### ISSUE THREAD

**Issue by mhsh64** [Azure/application-gateway-kubernetes-ingress#919]
**Describe the bug**

We are getting the bellow error on each Listener configured by AGIC:
This Basic HTTP listener cannot use the same frontend port as an existing listener.
 
Why this is happening. In our Ingress resources we have used bellow annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: mycertname
 
And the following used for parameters during AGIC installation:
      - APPGW_VERBOSITY_LEVEL="3"
      - HTTP_SERVICE_PORT="8123"
      - USE_PRIVATE_IP="true"
      - AZURE_ENVIRONMENT="AZUREPUBLICCLOUD"
      - APPGW_SUBSCRIPTION_ID="${SUBSCRIPTIONID}"
      - APPGW_RESOURCE_GROUP="${APPGW_RG}”
      - APPGW_NAME="${APPGW_NAME}"
      - APPGW_SUBNET_NAME="${APPGW_SUBNET}”
      - USE_MANAGED_IDENTITY_FOR_POD="true"
 
Any solution?
No error is AGIC pod logs or on AppGW. Everything is fine, however we have that above error on each listener, since we have deployed three Ingress resource, AGIC configured three Listener on PORT 443 and with the certificate. I see also the listener configured as BASIC. 
 
Any idea how to handle this case?

I am using AppGw waf v2 and Agic latest image
**To Reproduce**
Deploy multiple ingress resource, Agic should configure multiple BASIC listeners on port 443 but when you look at the portal on each listener it says that above error
**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
* Output of `kubectl logs <ingress controller>. 
* Any Azure support tickets associated with this issue.

**Comment by 3quanfeng** [comment]
Hi @mhsh64 , listener is uniquely identified by hostname and port, for you case, you will need to use different hostname for each of the ingress with the same port

**Comment by mhsh64** [comment]
@3quanfeng thanks
Sorry I dis not get , should I use any specific annotations in INGRESS resource?

Each of our Ingress resources have their own unique Host name under Spec field. But AGIC is configuring AppGw with basic listener

Appreciate if you help me to understand how to configure our ingress resources

**Comment by mhsh64** [comment]
That is weird, because when I export the appGw arm template, I see my ‘Ingress host names’ are populated in “hostNames” of the template, but it does not show if the listener is Basic or Multi Site.

But in Portal, when I click on the same listener, it shows me this error:
‘This Basic HTTP listener cannot use the same frontend port as an existing listener’
And shows the Listener is Basic

@3quanfeng any idea and help please

**Comment by 3quanfeng** [comment]
Hi @mhsh64 , the portal issue is a known issue since rc2, please check the release not [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/CHANGELOG/CHANGELOG-1.2.md#v120-rc2)
In addition, can you please help share one of your ingress specification?

**Comment by mhsh64** [comment]
@3quanfeng thanks for confirmation 

Here is my sample Ingress

`apiVersion: extensions/v1beta1

kind: Ingress

metadata:

  name: myapp

  namespace: ns1

  annotations:

    kubernetes.io/ingress.class: azure/application-gateway

    appgw.ingress.kubernetes.io/appgw-ssl-certificate: mycert

    appgw.ingress.kubernetes.io/ssl-redirect: "true"

spec:

  tls:

    - hosts:

      - myapp.mydomain.com

  rules:

  - host: myapp.mydomain.com

    http:

      paths:

      - path: /

        backend:

          serviceName: myservice
          servicePort: 80 `

**Comment by mhsh64** [comment]
@3quanfeng Also Have another question, one of the main reason we want to use AGIC rather than NGINX controller is, we do not want to import certificate and secrets in Aks cluster, however, if I want to have end to end ssl encryption between AppGW and Backend Pods, do we need to import certificate as a Secret on the Cluster and refering in Ingress resource?

**Comment by 3quanfeng** [comment]
Hi @mhsh64 , the annotation will be ignored when you specify TLS spec in your ingress, please refer to [appgw-ssl-certificate ](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/annotations.md#appgw-ssl-certificate)
If you specify backend-protocol with https, you will need to probe your traffic port at 443, more please refer to [probe](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/features/probes.md)

**Comment by mhsh64** [comment]
Hi @3quanfeng 
Thanks, I removed tls spec
However my issue is for e2e encryption, see I used the sample app with annotations to make appgw to backend pods encrypted, however, I am getting 502 during curl and also backend unhealthy from portal. Did I miss anything in here?
I see almost the same issue on #875 



```
apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp

  namespace: ns2

  labels:

    app: aspnetapp

spec:

  containers:

  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"

    name: aspnetapp-image

    ports:

    - containerPort: 443

      protocol: TCP

---

apiVersion: v1

kind: Service

metadata:

  name: aspnetapp

  namespace: ns2

spec:

  selector:

    app: aspnetapp

  ports:

  - protocol: TCP

    port: 443

    targetPort: 443

---

apiVersion: extensions/v1beta1

kind: Ingress

metadata:

  name: aspnetapp

  namespace: ns2

  annotations:

    kubernetes.io/ingress.class: azure/application-gateway

    appgw.ingress.kubernetes.io/appgw-ssl-certificate: mycert

    appgw.ingress.kubernetes.io/ssl-redirect: "true"

    appgw.ingress.kubernetes.io/backend-protocol: "https"

    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "myrootcert"

spec:

  rules:

  - host: appgw-ns2.mydomain.com

    http:

      paths:

      - path: /

        backend:
          serviceName: aspnetapp
          servicePort: 443
```
