### ISSUE TITLE
Backend path prefix - 502 bad gateway 

### ISSUE THREAD

**Issue by tarunnarang0201** [Azure/application-gateway-kubernetes-ingress#924]
I am bit confused the way path resolves the endpoint, does it show in any logs the final endpoint it creates. I am stuck with this. Below is the endpoint which I wanted to call:-

https://hostname/api/orders/employees. And to call this endpoint through Ingress application gateway, this is how I configured but it returns 502 bad gateway error.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ordersapi
  namespace: orders
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard.apps.com"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: orders.apps.com
    http:
      paths:
      - path: /api/orders/employees
        backend:
          serviceName: orderservice
          servicePort: 80

```

**Comment by akshaysngupta** [comment]
@tarunnarang0201 Is your application running "/" ?
You should add `appgw.ingress.kubernetes.io/backend-path-prefix: "/"` to the annotations.

This will also adjust the health probe to probe your application at "/" instead of "/api/orders/employees"

**Comment by tarunnarang0201** [comment]
@akshaysngupta @3quanfeng - Forgive me, I should have added more details initially. Backend application works fine and contains some of the restful services mentioned below and their endpoints are such as -

> http://hostname/api/orders/employees
> http://hostname/api/Lookup/officeHierarchy
> http://hostname/api/Department/codes
> http://hostname/api/position/members

  Now if you see, these different endpoints starts with prefix "/api/" and then the controller name and actions. 
Here **Expected Result** is
If any of these endpoints are called (via HTTP Get), data should be returned but it fails.

**Investigation done so far**
As suggested by @akshaysngupta,I added the prefix and did some changes to it. Thus If I configure my ingress like below, it **returns the result successfully** for only one specific endpoint - > 
**curl -v http://orders.apps.com/api/orders/employees** returns 200 but fails for others.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ordersapi
  namespace: orders
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/api/orders/employees"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard.apps.com"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: orders.apps.com
    http:
      paths:
      - path: /api/orders/employees
        backend:
          serviceName: orderservice
          servicePort: 80
```
Thus , to make all endpoints works, I did the below changes in the above mentioned ingress file  but calling
**curl -v http://orders.apps.com/api/orders/employees** returns 404. And the same goes with other endpoints like
**curl -v http://orders.apps.com/api/department/codes** returns 404. 

As per my understanding, by doing the below changes - "path - /api/*" should be overwritten to the path - **/api/orders/employees** being called but it does not. 

```

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ordersapi
  namespace: orders
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/api/"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard.apps.com"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: orders.apps.com
    http:
      paths:
      - path: /api*
        backend:
          serviceName: orderservice
          servicePort: 80
```

Your suggestions are appreciated.
Thanks

**Comment by tarunnarang0201** [comment]
Is there no solution to it?

**Comment by 3quanfeng** [comment]
Hi @tarunnarang0201 ,did you try with defining multiple paths without backend-path-prefix , e.g.
http:
 paths:
 - path: /api/order/employees
    backend:
       serviceName: orderservice
       servicePort: 80
 - path: /api/position/members
    backend:
       serviceName: positionservice
       servicePort: 80

if your service has heathy check on "/" or "/api", then you could use it as backend-path-prefix.

**Comment by tarunnarang0201** [comment]
Yes multiple paths worked but I have 20 services, do I need to mention 20 services in this way.

h

**Comment by 3quanfeng** [comment]
Hi @tarunnarang0201 , if your web service exposes healthy check on "/" or "/api", then you could config either as backend-path-prefix, appgw will use it as a health probing, in this case, you could define path wildcard in your ingress e.g. /api/*

**Comment by tarunnarang0201** [comment]
Awesome, Thanks @3quanfeng , it worked. Below is the manifest file for reference:-

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ordersapi
  namespace: orders
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/api/"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "wildcard.apps.com"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: orders.apps.com
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: orderservice
          servicePort: 80
```
