### ISSUE TITLE
Support faster updates through AppGW

### ISSUE THREAD

**Issue by akshaysngupta** [Azure/application-gateway-kubernetes-ingress#926]
Connect AppGW directly to the AKS cluster to fetch backend pool updates. This is to reduce the 502s that happen during the rolling updates.

**Comment by nreddipalle** [comment]
@akshaysngupta any ETA on this?? We are using AGIC for our prod workloads extensively and noticing occasional 500 errors during deployments. we already followed and implemented the steps stated here: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/minimize-downtime-during-deployments.md
1. Pre-stop hook to sleep for 120 sec.
```
preStop:
              exec:
                command:
                  - "powershell.exe"
                  - "-command"
                  - "Start-Sleep -s 120"
```
2. connection draining timeout for 300 sec appgw.ingress.kubernetes.io/connection-draining-timeout: "300"
3. termination grace period seconds to 150 sec. terminationGracePeriodSeconds: 150
