### ISSUE TITLE
Ingress does not work with windows node pool

### ISSUE THREAD

**Issue by bilekt3** [Azure/application-gateway-kubernetes-ingress#936]
**Describe the bug**
Application gateway does not work with services on Windows node pool (tested on 1.2.0 version, same for RC2,RC3).

**To Reproduce**
Span test AKS with following configuration:

- RBAC enabled
- Advanced networking
- Attached second node pool based on windows
- Create service principal for settings
- Separate network for Application Gateway
- Public IP for Application Gateway
- Peering between AKS VNET and Application Gateway VNET  

Services:
```yaml
apiVersion: v1
kind: Service
metadata:
  ## This is service for Windows nodes
  name: api-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-api
---
apiVersion: v1
kind: Service
metadata:
  # This is service for Linux nodes
  name: gui-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-gui
    tier: frontend
```

When I create busy box in cluster everything is reachable (both services and pods)

Ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: websupervisor-ingress-agic
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: api-svc
              servicePort: 80
          - path: /
            backend:
              serviceName: gui-svc
              servicePort: 80
```

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

```
Name:         ingress-azure-669bd9976f-w2rlg
Namespace:    default
Priority:     0
Node:         aks-agentpool-18243249-vmss000000/10.240.0.97
Start Time:   Thu, 02 Jul 2020 18:23:51 +0200
Labels:       app=ingress-azure
              pod-template-hash=669bd9976f
              release=ingress-azure
Annotations:  checksum/config: ed09d2541185332d1382c366b6472ab7530c936a9c96472fb2055f8011579cc5
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.240.0.111
IPs:
  IP:           10.240.0.111
Controlled By:  ReplicaSet/ingress-azure-669bd9976f
Containers:
  ingress-azure:
    Container ID:   docker://f9fbfa968f4b723b1e681da76af4ed2564d0aff8adef003d37d6519435d599f7
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:de458f962eab0cd2de19d23dfeb9a0e4bc2565a38f8c45cc98a74f3cda8b940c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 02 Jul 2020 18:24:03 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-669bd9976f-w2rlg (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
      AZURE_AUTH_LOCATION:            /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-j7lvz (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  ingress-azure-token-j7lvz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-j7lvz
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From                                        Message
  ----    ------     ----       ----                                        -------
  Normal  Scheduled  <unknown>  default-scheduler                           Successfully assigned default/ingress-azure-669bd9976f-w2rlg to aks-agentpool-18243249-vmss000000
  Normal  Pulling    17m        kubelet, aks-agentpool-18243249-vmss000000  Pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0"
  Normal  Pulled     17m        kubelet, aks-agentpool-18243249-vmss000000  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0"
  Normal  Created    16m        kubelet, aks-agentpool-18243249-vmss000000  Created container ingress-azure
  Normal  Started    16m        kubelet, aks-agentpool-18243249-vmss000000  Started container ingress-azure
```

* Output of `kubectl logs <ingress controller>. 

```
ERROR: logging before flag.Parse: I0702 16:24:03.757636       1 utils.go:115] Using verbosity level 1 from environment variable APPGW_VERBOSITY_LEVEL
I0702 16:24:03.797379       1 environment.go:240] KUBERNETES_WATCHNAMESPACE is not set. Watching all available namespaces.
I0702 16:24:03.797487       1 auth.go:37] Creating authorizer from file referenced by environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0702 16:24:03.797524       1 httpserver.go:57] Starting API Server on :8123
I0702 16:24:04.131058       1 main.go:175] Ingress Controller will observe all namespaces.
I0702 16:24:04.259919       1 context.go:132] k8s context run started
I0702 16:24:04.259994       1 context.go:176] Waiting for initial cache sync
I0702 16:24:04.360289       1 context.go:189] Initial cache sync done
I0702 16:24:04.360330       1 context.go:190] k8s context run finished
I0702 16:24:04.360495       1 worker.go:39] Worker started
I0702 16:24:25.139387       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0702 16:24:25.140462       1 controller.go:151] Completed last event loop run in: 20.779815183s
I0702 16:24:26.248035       1 controller.go:151] Completed last event loop run in: 107.464495ms
I0702 16:26:15.603088       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0702 16:26:15.604317       1 controller.go:151] Completed last event loop run in: 20.502215963s
```
* Any Azure support tickets associated with this issue.
N/A
