### ISSUE TITLE
How to configure AGIC behind Front Door using host ingress rules

### ISSUE THREAD

**Issue by kamilzzz** [Azure/application-gateway-kubernetes-ingress#960]
Scenario:
Azure Front Door -> Application Gateway -> AKS cluster

Front Door in front of Application Gateway because we will have AKS clusters in multiple regions as a failover.

Kubernetes definitions:
```
apiVersion: v1
kind: Pod
metadata:
  name: sample1
  labels:
    app: sample1
spec:
  containers:
  - image: "registry.azurecr.io/sample-1:1"
    name: sample1-image
    ports:
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sample1
spec:
  selector:
    app: sample1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sample1
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: sample1.something.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sample1
          servicePort: 80
```

*.something.com configured as a wildcard frontend hostname for Azure Front Door.

Accessing Application Gateway IP directly with Host header set to value "sample1.something.com" works correctly as expected.
When the same url is accessed directly through Azure Front Door then Application Gateway doesn't know where to route requests.

I guess this is because AFD is overriding Host header and passing original host (sample1.something.com) as an X-Forwarded-Host header.

Is this scenario supported?
