### ISSUE TITLE
AGIC generating random listener names since last week.

### ISSUE THREAD

**Issue by vishal8k** [Azure/application-gateway-kubernetes-ingress#962]
**Describe the bug**
AGIC used to generate meaningful listener names such as `"fl-<hostname>-<portno>-<public/privateip>"`. This is what everyone wants. but for the past two weeks AGIC has been generating random listener names such as `"fl-5222170d53815f835f3b17c2c8904019"`. This behavior is seen exactly from the date Azure released a new feature for App gateway whose details can be found in the below link. 

https://docs.microsoft.com/en-us/azure/application-gateway/multiple-site-overview

however this has so far not affected the base functioning of AGIC. Ingress yaml I'm using is very normal and not anything new which I'm posting below.

```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: myingress
  namespace: mynamespace
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
spec:
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-service
              servicePort: 80
```

**Kubernetes Version:** 1.15.11
