### ISSUE TITLE
Multiple ingress routes create multiple listeners on AGW port 80?

### ISSUE THREAD

**Issue by bhartm3** [Azure/application-gateway-kubernetes-ingress#973]
**Describe the bug**
When we deploy two separate sample apps with a host based ingress rule, the ingress controller creates two listeners on the application gateway both on port 80. Is this the expected behavior?

**To Reproduce**
```
apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "neilpeterson/aks-helloworld:v1"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 3
      timeoutSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 81
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - backend:
              serviceName: aspnetapp
              servicePort: 81
```

```
apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp2
  labels:
    app: aspnetapp2
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp2-image
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 3
      timeoutSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp2
spec:
  selector:
    app: aspnetapp2
  ports:
  - protocol: TCP
    port: 82
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp2
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: bar2.com
      http:
        paths:
          - backend:
              serviceName: aspnetapp2
              servicePort: 82
```

**Ingress Controller details**
```
Name:         ingress-azure-1596716976-b65d8d6b4-7mm9q
Namespace:    default
Priority:     0
Node:         aks-agentpool-14866480-vmss000001/15.0.0.35
Start Time:   Thu, 06 Aug 2020 14:29:40 +0200
Labels:       aadpodidbinding=ingress-azure-1596716976
              app=ingress-azure
              pod-template-hash=b65d8d6b4
              release=ingress-azure-1596716976
Annotations:  checksum/config: bd3822e16a51f0cc7f98d3d3c350f02d72662013be8b4d259fadb431524dbd71
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           15.0.0.51
IPs:
  IP:           15.0.0.51
Controlled By:  ReplicaSet/ingress-azure-1596716976-b65d8d6b4
Containers:
  ingress-azure:
    Container ID:   docker://e6e2ff888cff0659546330a499feb0de574055a16822d44b5d6196b94fd994d5
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:de458f962eab0cd2de19d23dfeb9a0e4bc2565a38f8c45cc98a74f3cda8b940c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Thu, 06 Aug 2020 14:29:55 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure-1596716976  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-1596716976-b65d8d6b4-7mm9q (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-1596716976-token-bzbsb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-1596716976-token-bzbsb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-1596716976-token-bzbsb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
The created listeners:
![image](https://user-images.githubusercontent.com/14157527/89630478-bbc6f780-d89f-11ea-9639-06b467a74ccb.png)

![image](https://user-images.githubusercontent.com/14157527/89630519-cbded700-d89f-11ea-868e-33ac05f05f65.png)
