### ISSUE TITLE
Kubernetes livenessProbe not applied to AppGw configuration

### ISSUE THREAD

**Issue by kamilzzz** [Azure/application-gateway-kubernetes-ingress#987]
**Describe the bug**
I had a kubernetes deployment without a livenessProbe defined so Application Gateway configured a health probe with default values (path /, interval/timeout 30s, unhealthy threshold 3).

I've read document about minimizing downtime so now I have a livenessProbe specified and I've deployed a new version of my resources. Application Gateway config was updated but the health probe still contains default values (path /, interval/timeout 30s, unhealthy threshold 3).

YAML definition:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: <acr-name>.azurecr.io/api:2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: <app-gw-cert>
spec:
  rules:
    - host: <host1>
      http: &http_rules
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: 80
    - host: <host2>
      http: *http_rules
    - host: <host2>
      http: *http_rules
```

`kubectl describe` shows that kubernetes configured liveness probe correctly:
`Liveness:       http-get http://:80/healthz delay=0s timeout=3s period=5s #success=1 #failure=3`

I've observed this behavior on 2 separate clusters.
First version (without livenessProbe) was deployed yesterday.

**To Reproduce**

1. Create a deployment without a livenessProbe
2. AppGw health probe should be configured with default values
3. Update deployment to contain a livenessProbe
4. AppGw health probe config is not reflecting the livenessProbe (it should according to the doc - [minimizing downtime](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/minimize-downtime-during-deployments.md#solution))

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 

```
Name:         ingress-azure-7c6f89654c-k8ljt
Namespace:    default
Priority:     0
Node:         aks-default-42613148-vmss000000/10.0.0.4
Start Time:   Wed, 26 Aug 2020 16:31:42 +0200
Labels:       aadpodidbinding=ingress-azure
              app=ingress-azure
              pod-template-hash=7c6f89654c
              release=ingress-azure
Annotations:  checksum/config: b54d8ad83e7d5e8d6b3df51e28bc890c2df49433c0ea82415f9890c5e5c2c16c
              prometheus.io/port: 8123
              prometheus.io/scrape: true
Status:       Running
IP:           10.0.0.29
IPs:
  IP:           10.0.0.29
Controlled By:  ReplicaSet/ingress-azure-7c6f89654c
Containers:
  ingress-azure:
    Container ID:   docker://f774b6cfa9e17ba2376c54455be46eba14707e17992de84b5ee125a451127c03
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:1.2.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:de458f962eab0cd2de19d23dfeb9a0e4bc2565a38f8c45cc98a74f3cda8b940c
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 26 Aug 2020 16:31:51 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_CLOUD_PROVIDER_LOCATION:  /etc/appgw/azure.json
      AGIC_POD_NAME:                  ingress-azure-7c6f89654c-k8ljt (v1:metadata.name)
      AGIC_POD_NAMESPACE:             default (v1:metadata.namespace)
    Mounts:
      /etc/appgw/azure.json from azure (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-azure-token-vndbq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  azure:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  ingress-azure-token-vndbq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-azure-token-vndbq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

* Output of `kubectl logs <ingress controller>. 

```
I0826 14:50:02.764722       1 controller.go:151] Completed last event loop run in: 30.570734958s
I0827 19:21:19.876424       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0827 19:21:50.626575       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0827 19:21:50.626602       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0827 19:21:50.627496       1 mutate_app_gateway.go:204] END AppGateway deployment
I0827 19:21:50.627517       1 controller.go:151] Completed last event loop run in: 30.808981261s
I0827 19:21:51.757567       1 mutate_app_gateway.go:177] BEGIN AppGateway deployment
I0827 19:23:22.204476       1 mutate_app_gateway.go:185] Applied generated Application Gateway configuration
I0827 19:23:22.204497       1 mutate_app_gateway.go:200] cache: Updated with latest applied config.
I0827 19:23:22.205579       1 mutate_app_gateway.go:204] END AppGateway deployment
I0827 19:23:22.205602       1 controller.go:151] Completed last event loop run in: 1m30.577916377s
```

* AGIC version: 1.2.0
